<%@ Page Title=" Bíblia Online - 3º João - Capítulo 01   " Language="C#" MasterPageFile="~/PT/SitePTBook.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content=" O presbítero ao amado Gaio, a quem amo na verdade. Amado, oro para que você tenha boa saúde e tudo lhe corra bem, assim como vai bem a sua alma. Muito me alegrei ao receber a visita de alguns irmãos que falaram a respeito da sua fidelidade, de como você continua andando na verdade. Não tenho alegria maior do que ouvir que meus filhos estão andando na verdade." /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>                  
        <div class='col-xs-12 col-md-12 text-center'>            
            <h1> 3º João - Capítulo 01 	</h1>      <br />          </div>
          <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
        <div class="bible verses"><p data-v="nvi:64:1:1" class=""><sup>1</sup> <span class="text">O presbítero ao amado Gaio, a quem amo na verdade.</span></p><p data-v="nvi:64:1:2" class=""><sup>2</sup> <span class="text">Amado, oro para que você tenha boa saúde e tudo lhe corra bem, assim como vai bem a sua alma.</span></p><p data-v="nvi:64:1:3" class=""><sup>3</sup> <span class="text">Muito me alegrei ao receber a visita de alguns irmãos que falaram a respeito da sua fidelidade, de como você continua andando na verdade.</span></p><p data-v="nvi:64:1:4" class=""><sup>4</sup> <span class="text">Não tenho alegria maior do que ouvir que meus filhos estão andando na verdade.</span></p><p data-v="nvi:64:1:5" class=""><sup>5</sup> <span class="text">Amado, você é fiel no que está fazendo pelos irmãos, apesar de lhe serem desconhecidos.</span></p><p data-v="nvi:64:1:6" class=""><sup>6</sup> <span class="text">Eles falaram à igreja a respeito deste seu amor. Você fará bem se os encaminhar em sua viagem de modo agradável a Deus,</span></p><p data-v="nvi:64:1:7" class=""><sup>7</sup> <span class="text">pois foi por causa do Nome que eles saíram, sem receber ajuda alguma dos gentios.</span></p><p data-v="nvi:64:1:8" class=""><sup>8</sup> <span class="text">É, pois, nosso dever receber com hospitalidade a irmãos como esses, para que nos tornemos cooperadores em favor da verdade.</span></p><p data-v="nvi:64:1:9" class=""><sup>9</sup> <span class="text">Escrevi à igreja, mas Diótrefes, que gosta muito de ser o mais importante entre eles, não nos recebe.</span></p><p data-v="nvi:64:1:10" class=""><sup>10</sup> <span class="text">Portanto, se eu for, chamarei a atenção dele para o que está fazendo com suas palavras maldosas contra nós. Não satisfeito com isso, ele se recusa a receber os irmãos, impede os que desejam recebê-los e os expulsa da igreja.</span></p><p data-v="nvi:64:1:11" class=""><sup>11</sup> <span class="text">Amado, não imite o que é mau, mas sim o que é bom. Aquele que faz o bem é de Deus; aquele que faz o mal não viu a Deus.</span></p><p data-v="nvi:64:1:12" class=""><sup>12</sup> <span class="text">Quanto a Demétrio, todos dão bom testemunho dele, inclusive a própria verdade. Nós também damos, e você sabe que o nosso testemunho é verdadeiro.</span></p><p data-v="nvi:64:1:13" class=""><sup>13</sup> <span class="text">Tenho muito que lhe escrever, mas não desejo fazê-lo com pena e tinta.</span></p><p data-v="nvi:64:1:14" class=""><sup>14</sup> <span class="text">Espero vê-lo em breve, e então conversaremos face a face.</span></p><p data-v="nvi:64:1:15" class=""><sup>15</sup> <span class="text">A paz seja com você. Os amigos daqui lhe enviam saudações. Saúde os amigos daí, um por um.</span></p></div>
              		
         </div>        
          <div class="bg-info container-fluid col-xs-12">    <h5 class='text-center'>  Bíblia Online - 3º João - Links para os Capítulos    </h5>   </div> 
          <div class="text-center"><ul class="pagination pagination-lg">    <!--  class="active"  -->            
              <li   class="active" ><a href="Joao-03-Capitulo-01">01</a></li>              
          </ul>
        </div>
 </div>          
</asp:Content>
