<%@ Page Title="50. Descolonisation of Africa" Language="C#" MasterPageFile="~/EN/SiteENHistory.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">
       <meta name="description" content="In the late Middle Ages the states of Europe began to..." /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
     <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>
            <br><h1>                                            
	               50. Descolonisation of Africa         
			</h1><br><br> 
            <div class='text-justify' style='line-height:1.7'>
              <p><span class="lead">  
              In the late Middle Ages the states of Europe began to
              </span>      
                      
              
 discover Africa and found therein kingdoms or states. The first contacts with these people were not immediately rule, but any trade. However, the conflicts generated by competition among several European powers led to domination in the nineteenth century, and generally the destruction of kingdoms, a process which culminated in the sharing of the continent by European states at the Berlin Conference in 1885.</p><p>
However, the two world wars in the twentieth century have left those countries unable to maintain economic and military dominance in its colonies. These problems led the former colonial powers to negotiate the independence of the colonies.</p><p>
Despite all the union between the peoples of Africa, signed at the Conference of the Peoples of Africa, the independence of some countries, such as Algeria and the Democratic Republic of Congo, was achieved only after exhausting conflict that stretched for up to years of war.</p><p>
France in 1960 recognized the independence of most African colonies such as Tunisia, Morocco and Algeria.</p><p>
Italy was the last European country to reach the African continent and also the first to retire. The only Italian colonies in Africa were Libya and Somalia. The independence of the former Italian colonies proceeded early in the post-war, with the UN an important role in this scenario.</p><p>
The independence of the Portuguese colonies in Africa started in 1973 with the unilateral declaration of the Republic of Guinea Bissau. The remaining Portuguese colonies amounted to independence in 1975, following the Carnation Revolution.</p><p>
Spain colonized which corresponds today to the current northern Morocco, Equatorial Guinea and the Western Sahara. The current Morocco became independent in 1956 and Equatorial Guinea became independent in 1968.</p><p>
The present territory of Western Sahara gained independence on 27 February 1976. However, its independence was not and still is not recognized by the UN. Only 60 countries have recognized its independence.</p><p>
In regions of English colonization, decolonization was characterized in general by peaceful break. This was the case, for example, Ghana, Nigeria, Sierra Leone and Gambia. In Kenya, however, the political emancipation was preceded by violent conflicts due to the resistance of the white population. Total Independence of South Africa was in 1931.
                                    
			</p>            
       
	      </div><br><br><br><br>                  
 	  <img class="img-responsive" style="margin:0 auto;" src="http://www.sanderlei.com.br/img/historia/50-01-Descolonização-da-Africa.jpg" width="600" height="400" alt="50. Descolonisation of Africa"/>        
        <br><br><br></div>
     </div>
</asp:Content>
