<%@ Page Title="Machado de Assis -  A semana  " Language="C#" MasterPageFile="~/PT/SitePTMachado.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content="  Machado de Assis - A semana - Crônica  " /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>            
            <br />
            <h1>  Machado de Assis - Crônica</h1>
            <br /> 
              <!-- INICIO - VIDEO do YOUTUBE 
               <div class="container-fluid">	            
                <div class='col-xs-12 col-sm-6 col-sm-offset-3 text-center'> 
                    <div class="embed-responsive embed-responsive-16by9" >
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/" frameborder="0" allowfullscreen ></iframe>
                    </div>  
               </div></div>
              FIM - VIDEO do YOUTUBE  -->
        </div>       
        <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
             <br /> <h2 class='text-center'>   Machado de Assis - A semana   </h2>        <br /> 
                        
            
  <br />
      <h3>1897 </h3>
  <br />
<h4>3 de janeiro </h4>
  <br />
<p>A importância da carta que se vai ler devia excluir qualquer outro cuidado esta semana; mas não se perde nada em retificar um lapso. Pequeno lapso: domingo passado escrevi “autor de Fleurs du Mal” onde devera escrever “autor de Blasphèmes”, tudo porque uma estrofe de Baudelaire me cantava na memória para corrigir com ela o seu patrício Richepin. Vamos agora à carta. Recebi-a anteontem de um cidadão americano, o Rev. M. Going, que aqui chegou em agosto do ano findo e partiu a 1 ou 2 de setembro para a ilha da Trindade. — “Suspeito uma coisa”, disse-me ele. — “Que coisa?” — “Não posso dizer; se acertar, terei feito uma grande descoberta, a maior descoberta marítima do século; se não acertar, fica o segredo comigo.” Podes imaginar agora, leitor, o assombro com que recebi a epístola que vais ler: </p>

<p>“Ilha da Trindade, 26 de dezembro de 1896. </p>

<p>Caro senhor. — Esta carta vos será entregue pelo Rev. James Maxwell, de Nebrasca. Veio ele comigo a esta ilha, sem saber o fim que me trouxe a ela. Pensava que o meu desejo era conhecer o valor do penhasco que os ingleses queriam tomar ao Brasil, segundo lhe disse em Royal Hotel, 3, Rua Clapp, uma sexta-feira. O Rev. Maxwell vos contará o assombro em que ficou e a minha desvairada alegria quando vimos o que ele não esperava ver, o que absolutamente ninguém pensou nem suspeitou nunca. </p>

<p>Senhor, esta ilha não é deserta, como se afirma; esta ilha tem, do lado oriental, uma pequena cidade, com algumas vilas e aldeias próximas. Eu desconfiava disto, não por alguma razão científica ou confidência de navegante, mas por uma intuição fundada em tradição de família. Com efeito, é constante na minha família que um dos meus avós, aventureiro e atrevido, deixou um dia as costas da Inglaterra, entre 1648 e 1650, em um velho barco, com meia dúzia de tripulantes. Voltou dez anos depois, dizendo ter descoberto um povo civilizado, bom e pacífico, em certa ilha que descreveu. Não temos outro vestígio; mas, não sei por que razão, — creio que por inspiração de Deus, — desconfiei que a ilha era a da Trindade. E acertei; eis a ilha, eis o povo, eis a grande descoberta que vai fechar com chave de ouro o nosso século de maravilhas. </p>

<p>As notícias atropelam-se-me debaixo da pena, de modo que não sei por onde continue. A primeira coisa que lhe digo já é que achei a prova da estada aqui de um Going, no século XVII. Dei com um retrato de Carlos I, meio apagado e conservado no museu da cidade. Disseram-me que fora deixado por um homem que residiu aqui há tempos infinitos. Ora, o meu avô citado era grande realista e por algum tempo bateu-se contra as tropas de Cromwell. Outra prova de que um inglês esteve aqui é a língua do povo, que é uma mistura de latim, inglês e um idioma que o Rev. Maxwell afirma ser púnico. Efetivamente, este povo inculca descender de uma leva de cartagineses que saiu de Cartago antes da vitória completa dos romanos. Uma vez entrados aqui, juraram que nenhuma relação teriam mais com povo algum da Terra, e assim se conservaram. Quando a população chegou a vinte e cinco mil almas, fizeram uma lei reguladora dos nascimentos, para que nunca esse número seja excedido; único modo, dizem, de se conservarem segregados da cobiça e da inveja do Universo. Não é essa a menor esquisitice desta pequena nação; outras muitas tem, e todas serão contadas na obra que empreendi. Porquanto, meu caro senhor, é meu intuito não ir daqui sem haver descrito os costumes e as instituições do pequenino país que descobri, dizendo de suas origens, raça, língua o mais que puder coligir e apurar. Talvez lhe traga dano. Não é fora de propósito crer que a Inglaterra, sabendo que aqui esteve um inglês, há dois séculos, reclame a posse da ilha; mas, em tal caso, sendo Going meu parente, reivindicarei eu a posse e vencerei por um direito anterior. De fato, todo ente gerado, antes de vir à luz, antes de ser cidadão, é filho de sua mãe, e até certo ponto é avô da geração futura que virtualmente traz em si. Vou escrever neste sentido a um legista de Washington. </p>

<p>Falei de esquisitices. Aqui está uma, que prova ao mesmo tempo a capacidade política deste povo e a grande observação dos seus legisladores. Refiro-me ao processo eleitoral. Assisti a uma eleição que aqui se fez em fins de novembro. Como em toda a parte, este povo andou em busca da verdade eleitoral. Reformou muito e sempre; esbarrava-se, porém, diante de vícios e paixões, que as leis não podem eliminar. Vários processos foram experimentados, todos deixados ao cabo de alguns anos. É curioso que alguns deles coincidissem com os nossos de um e de outro mundo. Os males não eram gerais, mas eram grandes. Havia eleições boas e pacíficas, mas a violência, a corrupção e a fraude inutilizavam em algumas partes as leis e os esforços leais dos governos. Votos vendidos, votos inventados, votos destruídos, era difícil alcançar que todas as eleições fossem puras e seguras. Para a violência havia aqui uma classe de homens, felizmente extinta, a que chamam pela língua do país, kapangas ou kapengas. Eram esbirros particulares, assalariados para amedrontar os eleitores e, quando fosse preciso, quebrar as urnas e as cabeças. Às vezes quebravam só as cabeças e metiam nas urnas maços de cédulas. Estas cédulas eram depois apuradas com as outras, pela razão especiosa de que mais valia atribuir a um candidato algum pequeno saldo de votos que tirar-lhe os que deveras lhe foram dados pela vontade soberana do país. A corrupção era menor que a fraude; mas a fraude tinha todas as formas. Enfim, muitos eleitores, tomados de susto ou de descrença, não acudiam às urnas. </p>

<p>Vai então, há cinqüenta anos (os nossos aqui são lunares) apareceu um homem de Estado, autor da lei que ainda vigora no país. Não podeis caro senhor, conceber nada mais estranho nem também mais adequado que essa lei: é uma obra-prima de legislação experimental. Esse homem de Estado, por nome Trumpbal, achou dificuldades em começo, porque a reforma proposta por ele mudava justamente o princípio do governo. Não o fez, porém, pelo vão gosto de trocar as coisas. Trumpbal observara que este povo confia menos em si que nos seus deuses; assim, em vez de colocar o direito de escolha na vontade popular, propôs atribuí-lo à Fortuna. Fez da eleição uma consulta aos deuses. Ao cabo de dois anos de luta, conseguiu Trumpbal a primeira vitória. — Pois bem, disseram-lhe; decretemos uma lei provisória, segundo o vosso plano; far-se-ão por ela duas eleições, e se não alcançar o efeito que esperais, buscaremos outra coisa. Assim se fez; a lei dura há quarenta e oito anos. </p>

<p>Eis os lineamentos gerais do processo: cada candidato é obrigado a fazer-se inscrever vinte dias antes da eleição, pelo menos, sem limitação alguma de número. Nos dez dias anteriores a eleição, os candidatos expõem na praça pública os seus méritos e examinam os dos seus adversários, a quem podem acusar também, mas em termos comedidos. Ouvi um desses debates. Conquanto a língua ainda me fosse difícil de entender, pude alcançar pelas palavras inglesas e latinas, pela compostura dos oradores e pela fria atenção dos ouvintes, que os oradores cumpriam escrupulosamente a lei. Notei até que, acabados os discursos, os adversários apertavam as mãos uns dos outros, não somente com polidez, mas com afabilidade. Não obstante, para evitar quaisquer personalidades, o candidato não é designado pelo próprio nome, mas pelo de um bicho, que ele mesmo escolhe no ato da inscrição. Um é águia, outro touro, outro pavão, outro cavalo, outro borboleta, etc. Não escolhem nomes de animais imundos, traiçoeiros, grotescos e outros, como sapo, macaco, cobra, burro; mas a lei nada impõe a tal respeito. Nas referências que fazem uns aos outros adotaram o costume de anexar ao nome um qualificativo honrado: o brioso Cavalo, o magnífico Pavão, o indomável Touro, a galante Borboleta, etc., fazendo dessas controvérsias, tão fáceis de azedar, uma verdadeira escola de educação. </p>

<p>A eleição é feita engenhosamente por uma máquina, um tanto parecida com a que tive ocasião de ver no Rio de Janeiro, para sortear bilhetes de loterias. Um magistrado preside a operação. Escrito o título do cargo em uma pedra negra, dá-se corda à máquina, esta gira e faz aparecer o nome do eleito, composto de grandes letras de bronze. Os nomes de todos, isto é, os nomes dos animais correspondentes têm sido postos na caixa interior da máquina, não pelo magistrado, mas pelos próprios candidatos. Logo que o nome de um aparecer, o dever do magistrado é proclamá-lo, mas não chega a ser ouvido, tão estrondosa é a aclamação do povo: </p>

<p>— “Ganhou o Pavão! ganhou o Cavalo!” Este grito, repetido de rua em rua, chega aos últimos limites da cidade, como um incêndio, em poucos minutos. O alvoroço é enorme, é um delírio. Homens, mulheres, crianças, encontram-se e bradam: — “Ganhou o Cavalo! ganhou o Pavão!” </p>

<p>Mas então os vencidos não gemem, não blasfemam, não rangem os dentes? Não, caro senhor, e aí está a prova da intuição política do reformador. Os cidadãos, levados pelo impulso que os faz não descrer jamais da Fortuna, lançam apostas, grandes e pequenas, sobre os nomes dos candidatos. Tais apostas parece que deviam agravar a dor dos vencidos, uma vez que perdiam candidato e dinheiro; mas, em verdade, não perdem as duas coisas. Os cidadãos fizeram disto uma espécie de perde-ganha; cada partidário aposta no adversário, de modo que quem perde o candidato ganha o dinheiro, e quem perde o dinheiro ganha o candidato. Assim, em vez de deixar ódios e vinganças, cada eleição estreita mais os vínculos políticos do povo. Não sei se uma grande cidade poderia adotar tal sistema; é duvidoso. Mas para cidades pequenas não creio que haja nada melhor. Tem a doçura, sem a monotonia do víspora. E, deixai-me que vo-lo diga francamente, apelando para os seus deuses, este povo, que conserva as crenças errôneas da raça originária, pensa que são eles que o ajudam; mas, em verdade, é a Providência Divina. Ela é que governa a Terra toda e dá luz à escuridão dos espíritos. Está em Isaías: “Ouvi, ilhas, e atendei, povos de longe.” Está nos Salmos: “Do Senhor é a redondeza da Terra e todos os seus habitadores, porque ele a fundou sobre os mares e sobre os rios.” </p>

<p>Haveria muito que dizer se pudesse contar outros costumes deste povo, fundamentalmente bom e ingênuo; mas paro aqui. Conto estar de volta no Rio de Janeiro em fins de maio ou princípios de junho. Peço-vos que auxilieis o meu amigo Rev. Maxwell; ele vai buscar-me alguns livros e um aparelho fotográfico. Indagai dele as suas impressões, e ouvireis a confirmação do que vos digo. Adeus, meu caro senhor; crede-me vosso muito obediente servo — GOING.” </p>

<p>O Rev. Maxwell confirma realmente tudo o que me diz a carta do Rev. Going. São dois sacerdotes; e, embora protestantes, não creio que se liguem para rir de um homem de boa-fé. É tudo, porém, tão extraordinário que, para o caso de ser um simples humbug, resolvi publicar a carta. Os entendidos dirão se é possível a descoberta. </p>

<p>10 de janeiro Falemos de doenças, de mortes, de epidemias. Não é alegre, mas nem todas as coisas o são, e algumas há mais melancólicas que outras. Estamos em pleno estio, estação dos grandes obituários, que por ora não sobem da usual craveira; morre-se como em maio e setembro. A velha hóspede importuna (não é preciso dizer) ainda se não levantou da cama; pode ser até que lá fique. Também há anos em que, por se levantar tarde, não come menos, ainda que mais depressa; mas esperemos o melhor. </p>

<p>Apesar de tudo, o conselho municipal votou, creio eu, a lei do empréstimo de saneamento. Não afirmo que sim nem que não, porque é mui difícil para mim extrair de um longo debate o que é que realmente se votou ou não votou. Quando os vereadores falavam uns para os outros, e só eram conhecidos cá fora os votos coletivos, poder-se-iam ter presentes as leis, então chamadas posturas, e mal chamadas assim. As galinhas não põem silenciosamente os ovos; cacarejam sempre. Ora, os vereadores punham calados as suas leis. Também não se lhes sabia a opinião, e podiam pensar diversamente no princípio e no fim de agosto, conquanto fossem firmes todo o ano; mas podiam. Agora que, por uma razão justa, os discursos são apanhados, impressos, postos em volume, tudo se sabe do debate, o que é dele e o que não é. Mas vá um homem tomar pé no meio de tantas orações! </p>

<p>Demais, o contribuinte, bem examinado, não quer saber de orçamentos nem de empréstimos. O contribuinte sou eu, és tu; tu és um homem que gostas de dizer mal, de ler veementes discursos, mormente se trazem muitos apartes e não tratam da matéria em discussão, espírito fluido, avesso às asperezas de imposto e às realidades da soma. Dêem-nos bons debates, algum escândalo, meia dúzia de anedotas, e o resto virá. Ninguém se há de negar a pagar os impostos. Quando forem muitos e grossos, que tornem a vida cara, farão o ofício do calor e da trovoada, que é dar princípio às conversações de pessoas que não tenham outra coisa que dizer. Iniciada a palestra, desaparecem. </p>

<p>Creio, porém, que está votado o empréstimo. Dado que sim, convirá proceder já às obras, ou será melhor esperar que o mal comece? Tudo está em saber o que é </p>

<p>o mal. Aparentemente é só aquela visita de 1850, que ainda não saiu cá de casa, por mais que recorramos às superstições da terra contra os cacetes; mas bem pode ser que haja outro: a arteriosclerose. Já se morre muito desta doença. Há coisa de dez ou quinze anos ninguém conhecia aqui semelhante flagelo, nem de figura, nem sequer de nome. Não conseguira transpor a barra: não pensava sequer nisso. Um dia, caiu não se sabe donde e pegou um descuidado, que não resistiu e foi para o obituário entre uma vítima de tuberculose e outra de tifo; estava em casa. Daí para cá, a arteriosclerose tem feito as suas vítimas certas. Outras doenças podem matar ou aleijar, e também podem não fazer nada, não aparecer sequer; aquela é segura. É sorrateira. Uma pessoa adoece, não mostra de quê, por mais que se investigue, apalpe, analise; dá-se-lhe tudo, contra vários males, e a vida diminui, diminui, até que se vai inteiramente. Só então o terrível mal põe a orelha de fora, e passa um defunto para o cemitério com esta pecha de haver dissimulado a causa da morte, última e mais hedionda das hipocrisias. </p>

<p>O que há pior nessa moléstia, não é decerto o nome. O nome é bonito, é científico, não é de pronúncia fácil, e dito de certo modo pode matar por si mesmo. Ora, é sabido que os nomes valem muito. Casos há em que valem tudo. Na política é que se vê o valor que podem ter as palavras, independente do sentido. Agora mesmo veio um telegrama não sei de que Estado, tratando das últimas eleições. Conta fatos condenáveis, atos de violência e de fraude, e, referindo-se ao governo do Estado, chama-lhe nefasto. Ninguém ignora o que é um telegrama, tudo se paga. Todos sabem que há adjetivos trágicos, próprios da grande correspondência, das proclamações, dos artigos de fundo, impróprios da via telegráfica. Nefasto pareceestar nesse caso. É palavra grossa, enérgica, expressiva, — um tanto gasta, é possível, como bandido e perverso; mas sempre serve. Por mais gasto que esteja, nefasto tem ainda certo vigor; maior uso tem perverso, e há muito quem o empregue com bom êxito. Bandido, que é o mais surrado dos três, tem na harmonia das sílabas alguma coisa que lhe compensa o uso; e não é a qualquer que se lança este nome de bandido. Tu não és bandido; eu não sou bandido. </p>

<p>Pois, meu amigo, o correspondente não hesitou em mandar nefasto pelo telégrafo. Tal é o efeito de um adjetivo de certa gravidade. A suposição de que o telégrafo só conta e resume os fatos, vê-se que é gratuita. Também as paixões andam por ele, e as paixões não se exprimem com algarismos e sílabas soltas e pecas. Paixões são paixões. Chamam nefasto ao nefasto, sublime ao sublime, e não olham a dinheiro para transmitir o termo próprio. Se se há de falar de um governo adverso sem se lhe chamar nefasto, também não se poderá dizer de um governo amigo que é benemérito; não se poderá dizer nada. O telégrafo fica sendo um serviço sem explicação, sem necessidade, mero luxo, e, em matéria de administração, luxo e crime são sinônimos. Tanto não é assim, que esta mesma semana tivemos outra amostra de telegramas. Li alguns que, depois de qualificarem certo ato com palavras duras e cortantes, concluíam por chamá-lo inqualificável. Dois ou três, ao contrário, começam por declará-lo inqualificável, e acabam dando-lhe as devidas qualificações — tudo por eletricidade, que é instantâneo. A contradição é só aparente; inqualificável aqui é um termo superlativo, cúmulo dos cúmulos, uma coisa que encerra todas as outras. Sem esta faculdade de fazer estilo, o telégrafo não passaria de um edital de praça, quando o que lhe cumpre é ser catálogo de leilão. </p>

<p>Tudo isto veio a propósito de quê? Ah! da arteriosclerose. Dizia eu que o pior desta moléstia não é o nome. Em verdade, o pior é que ninguém lhe escapa. Não conheço pessoa que diga de si haver estado muito mal de uma arteriosclerose; o enfermo sabe da enfermidade quando a notícia da morte está no obituário, e os obituários publicam-se com alguma demora. É mal definitivo. Talvez conviesse fazer escapar alguns atacados, ainda que por poucos meses, um ou dois anos. Não é muito, mas a maior parte da gente, tendo de escolher entre morrer agora ou em 1899, prefere a segunda data, quando menos com o pretexto de ver acabar o século. É uma idéia; um específico contra a arteriosclerose, não salvando a todos, mas uns cinco por cento, podia muito bem ser aplicado, sem deixar de enriquecer </p>

<p>o inventor, que afinal também há de morrer. </p>

<p>Realmente estou demasiado lúgubre. On ne parle ici que de ma mort, diz um personagem de não sei que comédia. Sacudamos as asas; fora com a poeira do cemitério. Venhamos à vida, ao saneamento. Uma folha estrangeira perguntava há pouco quais eram as duas condições essenciais da salubridade de uma cidade, e respondia a si mesma que eram a água corrente em abundância e a eliminação rápida dos resíduos da vida. Depois, com um riso escarninho, concluía que tudo estava achado há vinte séculos pelos romanos. E lá vinham os famosos aquedutos... Mas, entre nós, os aquedutos, com o trem elétrico por cima, dão a imagem de um progresso que os romanos nem podiam sonhar. E quanto aos banhos, não há de que se orgulhem os antigos. O atual chafariz da Carioca tem lavado muito par de pernas, muito peito, muita cabeça, muito ventre; na menor das hipóteses, muito par de narizes. Não tem nome de banho público, mas what's in a name? como diz a divina Julieta. </p>

<p>17 de janeiro </p>

<p>Semana de maravilhas, que pincel divino e diabólico a um tempo não seria necessário para reduzir-te a um símbolo? Triste coisa é a rebelião. A loucura é coisa tristíssima. Imaginemos agora a rebelião de loucos que deve ter sido a de anteontem, no hospício de Santiago. Horrível, três vezes horrível. Afirma a agência Havas que os loucos praticaram desatinos. Este pleonasmo é a mais dura das ironias que uma agência, seja ou não Havas, pode cometer contra pobres criaturas sem juízo; mas se a intenção do telegrama foi zombar dos ajuizados que se metem a rebeldes, não digo que a ocasião fosse própria, mas, enfim, a notícia é menos crua. Leram naturalmente que a força pública teve de acudir para abafar o movimento, não havendo outro recurso em tais casos, ainda que os revoltosos não tratassem de derribar as instituições políticas. Trocaram-se balas e cabeçadas. Vejo daqui os olhos dos rebeldes, vagos e tontos, e ouço as risadas de mistura com os urros. Um, mais doido que outro, dá em si com as pernas dele, e lança-se acima de um soldado, que o apara na ponta da baioneta; as tripas disparam pela barriga fora, também loucas, também rebeldes... </p>

<p>Em si mesma, a loucura é já uma rebelião. O juízo é a ordem, é a constituição, a justiça e as leis. Se há nele algum tumulto que perturbe a ordem, alguma imoralidade que desafie a justiça, e se as leis nem sempre recebem aquela obediência exata que há nos sonhos de Platão e de Campanela, tudo isso é passageiro, e, se dura, não dura sempre. A vida não é perfeita, meus irmãos. As mais belas sociedades coxeiam, às vezes, de um pé, e não raro de ambos. Mas coxear é uma coisa e quebrar as pernas é outra. A demência é a fratura das pernas; ou, continuando a primeira metáfora, malucar é rebelar-se. Que não será uma revolta de alienados? </p>

<p>Ao pé dessa maravilha, tivemos outra de espécie contrária: o tratado de arbitramento entre a Inglaterra e os Estados Unidos. Vários grandes homens, inclusive Rochefort, disseram dele coisas magníficas, e a opinião geral é que a guerra acabou, e que este ato é o maior do século. Para um século que madrugou com sangue e aprendeu a andar entre batalhas, este acabar decretando a paz universal e eterna é, na, verdade, uma grande maravilha. Eu, que fui educado na desconfiança dos tratados, confesso que hesitei um pouco. Certo, dois grandes países podem entender-se sobre o modo de dividir os bens do evento, acrescendo que, no presente caso, a vitória de um ou de outro é sempre a vitória da língua inglesa, com mais arcaísmos de um lado ou mais americanismos de outro, Macaulay ou Bancroft, — numa só palavra Shakespeare. Nem se trata de aspiração nova; a nossa Constituição a inclui entre os seus artigos, mas aparelha a nação para a guerra. A minha hesitação veio de... </p>

<p>Não digo donde veio a minha hesitação, uma vez que acabou. Sim, a guerra há de extinguir-se; natural é que comece a fazê-lo, e o caminho mais pronto é achar um processo que a substitua. Mas, por que não direi a causa da minha hesitação? Vinha da rapidez do ato. Se fosse milagre, bem; eu aprendi com La Palisse que o caráter do milagre é ser súbito. Mas este autor, por seus paradoxos, está tão desacreditado que não vale mais crer nele. E estou que a vitória final da indústria será como as da própria guerra, que tendia a acabar com meia dúzia de batalhas. Oh! a paz do mundo! Bem-aventurados os que a alcançarem, e é natural que sejam duas nações essencialmente industriais. Sim, venha a paz; a guerra será no campo da venda e da compra; eu quererei comprar barato, tu quererás vender caro, eis aí um vasto campo de luta, de emboscadas, de fortalezas mascaradas, de feridos e mortos. </p>

<p>Os exércitos serão principalmente os do imposto, e daqui passaria eu a outra maravilha da semana, que é o imposto municipal, se este não tivesse o inconveniente de ser municipal. Hoje estou fora da cidade. Concordo que os novos impostos são grossos e minuciosos, embora com fins declarados e certos, mas o meu espírito hoje é um vagabundo, que não quer parar em nada, menos ainda no Rio de Janeiro. Estou pronto a aceitar os exércitos do fisco, mas como princípio, como regra universal. As maravilhas hão de ser estranhas, como a daquele professor de Berlim, que está fabricando diamantes, e que o imperador visitou esta semana, para ver se o produto artificial vale o natural. Eu não descreio que a natureza venha a ser deposta e que as maravilhas da arte e da indústria substituam os seus produtos seculares. Um filósofo quer que a aventurina seja a única pedra que é pior natural que artificial; mas, além de não ser mineralogista, podia dizer verdades no seu tempo. Nós caminhamos e ainda havemos de fazer diamantes como fazemos a sesta. Um amigo meu, há quatro anos, mostrando-me um maço de ações de sua companhia, creio que de S. Lázaro, bradava-me: “Isto é ouro!” Na ocasião pareceu-me que era papel, papel excelente, a impressão boa, as cédulas iguais, tão iguais, que davam a impressão de um simples pedaço de madeira. Mas quem impede que ainda venha a ser ouro? </p>

<p>A cativa Bárbara é outra maravilha da semana, se é exato o que nos contou Teófilo Braga, no Jornal do Comércio, acerca da nova edição feita das Endechas a Bárbara, por Xavier da Cunha, a expensas do Dr. Carvalho Monteiro. Há tudo nessa reimpressão, há para poetas, há para bibliógrafos, há para rapazes. Os poetas lerão o grande poeta, os bibliógrafos notarão as traduções infinitas que se fizeram dos versos de Camões, desde o latim de todos até o guarani dos brasileiros, os rapazes folgarão com as raparigas da Índia. Estas (salvante o respeito devido à poesia e à bibliografia) não são das menores maravilhas, nem das menos fáceis, muitas lânguidas, todas cheirosas. Quanto às endechas à cativa, </p>

<p>Aquela cativa, 
Que me tem cativo, 
</p>

<p>como dizia o poeta, essas trazem a mesma galantaria das que ele compôs para tantas mulheres, umas pelo nome, Fuã Gonçalves, Fuã dos Anjos, etc., outras por simples indicações particulares, notando-se aquelas duas “que lhe chamaram diabo”, e aquelas três que diziam gostar dele, ao mesmo tempo, </p>

<p>Não sei se me engana Helena, 
Se Maria, se Joana; 
</p>

<p>ele concluía que uma delas o enganava, mas eu tenho para mim que era por causa da rima. A Pretidão de Amor (por alcunha) é que certamente lhe era fiel: </p>

<p>Olhos sossegados, 
Pretos e cansados. 
</p>

<p>Quanto ao trabalho de Xavier da Cunha e o serviço de Carvalho Monteiro, não há mais que louvar e agradecer, em nome das musas, conquanto não víssemos ainda nem um nem outro; mas a notícia basta. </p>

<p>24 de janeiro </p>

<p>Anteontem, quando os sinos começaram a tocar a finados, um amigo disse-me: “Um dos dois morreu, o arcebispo ou a papa.” Não foi o papa. Aquele velhinho transparente, com perto de noventa anos às costas, além do governo do mundo católico, continua a enterrar os seus cardeais. Agora mesmo, por telegrama impresso ontem, sabe-se que morreu mais um cardeal, com o qual sobem a cento e dezoito os que se têm ido da vida, enquanto Leão XIII fica à espera da hora que ainda lhe não bateu. Outro amigo meu, que já vira duas vezes o velho pontífice, acaba de escrever-me que o viu ainda uma vez, em dezembro, na cerimônia da imposição do chapéu a alguns novos cardeais. Descreve a forma da cerimônia, cheio de admiração e de fé, — uma fé sincera e singela, flor dos seus jovens anos. Ouvira uma missa ao papa, e, posto enfraquecido pela idade, este lhe pareceu resistir a ação do tempo. </p>

<p>Não sucedeu o mesmo ao digno arcebispo do Rio de Janeiro. Posto que muito mais moço, foi mais depressa tocado pela hora da morte. D. João era um lutador; as folhas do dia lembram ou nomeiam os livros e opúsculos que escreveu, não contando o trabalho de jornalista, obra que desaparece todos os dias com o sol, para recomeçar com o mesmo sol, e não deixar nada na memória dos homens, a não ser o vago sulco de um nome, que se apaga (para os melhores) com a segunda geração. Este homem, nado em Barcelona, filho de um belga e de uma senhora espanhola, — creio que era espanhola, — estava longe de crer que acabaria na sede arquiepiscopal de uma grande capital da América. Tais são os destinos, tais os ventos que levam a vela de cada um, — ou para a navegação costeira e obscura, ou para a descoberta remota e gloriosa. </p>

<p>Era um lutador. Eu confesso que a primeira e mais viva impressão episcopal que tenho não é de homem de combate, talvez porque a hora não era de combate. A impressão que me ficou mais funda foi a daquele D. Manuel do Monte Rodrigues, Conde de Irajá. A boca cheia de riso, como Frei Luís de Sousa refere de São Bartolomeu dos Mártires, os olhos pequenos, com a pouca luz restante, coados pelos vidros grossos dos óculos de ouro, a benção pronta, a mão já trêmula, o corpo já curvado, descia da sege episcopal, todo vestido de paz e sossego. Uma figura daquelas, na imaginação da criança, facilmente se liga à idéia da imortalidade. Um dia, porém, D. Manuel morreu. A terra, credor que não perdoa, e apenas reformará algumas letras, veio pedir-lhe a restituição do empréstimo. D. Manuel entregou-lho, aumentado dos juros de uma vida de virtudes e trabalhos. </p>

<p>Veio o moço D. Pedro, e com pouco soou a hora de combate, que foi longa e ruidosa. A parte dele não foi grande na luta; pelo menos, não teve igual eco aos outros. Nem por isso a imagem do primeiro bispo me ficou apagada pela do segundo, apesar do auxílio do tempo em favor de D. Pedro. </p>

<p>Não era a mansidão que conservava o relevo daquele. Nenhum lutador mais impetuoso, mais tenaz e mais capaz que D. Vital, bispo de Olinda, e a impressão que este me deixou foi extraordinária. Vi-o uma só vez, a porta do tribunal, no dia em que ele e o bispo do Pará tiveram de responder no processo de desobediência. </p>

<p>A figura do frade, com aquela barba cerrada e negra, os olhos vastos e plácidos, cara cheia, moça e bela, desceu da sege, não como o velho D. Manuel, mas com um grande ar de desdém e superioridade, alguma coisa que o faria contar como nada tudo o que se ia passar perante os homens. Sabe-se que morreu na Europa, creio que na Itália. Há quem acredite que voluntariamente não tornaria a cadeira de Pernambuco. Ao seu companheiro de então, o bispo do Pará, tive ocasião de vê-lo ainda, numa sala, familiar e grave, atraente e circunspeto, mas já sem aquele clangor das trombetas de guerra; a campanha acabara, a tolerância recuperara os seus direitos. </p>

<p>Também a luta para o arcebispo D. João não era a mesma; não havia a crise dos primeiros tempos em que se distinguiu. Era a luta de todos os dias, que a imprensa católica naturalmente mantém contra princípios e institutos que lhe são adversos, sem por isso concitar os fiéis à desobediência e à destruição. Leão XIII é </p>

<p>o modelo dessa defesa do dogma sem a agitação da guerra, tolerando o que uns chamam calamidade dos tempos, outros conquistas do espírito civil, mas que, sendo fatos estabelecidos, não há modo visível de os desterrar deste mundo. Quem esperará que a Igreja reconheça nenhum outro matrimônio, além do católico? Mas quem quererá que recuse a benção aos que se casam civilmente? Não é só o imposto que se dá a César, ou não é só o imposto em dinheiro; é também a obediência as suas leis. A Igreja protestará, mas viverá. </p>

<p>Este ponto prende com outro bispo, o do Rio Grande, que pregou agora em uma igreja de Santa Maria da Boca do Monte contra o casamento civil e contra os que se não confessam. Diz uma carta aqui publicada que foi tão violento em sua linguagem que o povo que enchia a igreja veio esperá-lo a porta e fez-lhe uma demonstração de desagrado. O correspondente chama-lhe — “charivari medonho”. Eu posso não entender bem nem mal a violência do bispo; mas o que ainda menos entendo é a dos fiéis. Que foram então os fiéis fazer ao templo onde pregava o bispo? Foram lá, porque são fiéis, porque estão na mesma comunhão de sentimentos religiosos. Se a tolerância lhes parecia conveniente, e a brandura necessária, era caso de discordar do bispo e até lastimá-lo, mas pateá-lo? Que fariam então os mais terríveis inimigos do Credo? Por que a pateada, “o charivari medonho” é a ultima ratio do desagrado. Alguns, considerando o bastão, pensarão que aquela é só penúltima. Mas nem uma nem outra razão é própria de católicos. Salvo se os fiéis que ouviam o bispo eram meros passeantes que entraram na igreja como em um parque aberto, para descansar a vista e os pés. Pode deduzir-se isto em desespero de causa; mas, francamente, não sei que pense. Folguemos em crer que o arcebispo agora morto não daria azo a tal explosão, não só por si, mas ainda pelo respeito em que o tinham. </p>


<H5>31 de janeiro </H5>

<p>Os direitos da imaginação e da poesia hão de sempre achar inimiga uma sociedade industrial e burguesa. Em nome deles protesto contra a perseguição que se está fazendo à gente de Antônio Conselheiro. Este homem fundou uma seita a que se não sabe o nome nem a doutrina. Já este mistério é poesia. Contam-se muitas anedotas, diz-se que o chefe manda matar gente, e ainda agora fez assassinar famílias numerosas porque o não queriam acompanhar. É uma repetição do crê ou morre; mas a vocação de Maomé era conhecida. De Antônio Conselheiro ignoramos se teve alguma entrevista com o anjo Gabriel, se escreveu algum livro, nem sequer se sabe escrever. Não se lhe conhecem discursos. Diz-se que tem consigo milhares de fanáticos. Também eu o disse aqui, há dois ou três anos, quando eles não passavam de mil ou mil e tantos. Se na última batalha é certo haverem morrido novecentos deles e o resto não se despega de tal apóstolo, é que algum vínculo moral e fortíssimo os prende até a morte. Que vínculo é esse? </p>

<p>No tempo em que falei aqui destes fanáticos, existia no mesmo sertão da Bahia o bando dos clavinoteiros. O nome de clavinoteiros dá antes idéia de salteadores que de religiosos; mas se no Corão está escrito que “o alfanje é a chave do céu e do inferno”, bem pode ser que o clavinote seja a gazua, e para entrar no céu tanto importará uma como outra; a questão é entrar. Não obstante, tenho para mim que esse bando desapareceu de todo; parte estará dando origem a desfalques em cofres públicos ou particulares, parte à volta das urnas eleitorais. O certo é que ninguém mais falou dele. De Antônio Conselheiro e seus fanáticos nunca se fez silêncio absoluto. Poucos acreditavam, muitos riam, quase todos passavam adiante, porque os jornais são numerosos e a viagem dos bonds é curta; casos há, como os de Santa Teresa, em que é curtíssima. Mas, em suma, falava-se deles. Eram matéria de crônicas sem motivo. </p>

<p>Entre as anedotas que se contam de Antônio Conselheiro, figura a de se dar ele por uma encarnação de Cristo, acudir ao nome de Bom Jesus e haver eleito doze confidentes principais, número igual ao dos apóstolos. O correspondente da Gazeta de Notícias mandou ontem notícias telegráficas, cheias de interesse, que toda gente leu, e por isso não as ponho aqui; mas, em primeiro lugar, escreve da capital da Bahia, e, depois, não se funda em testemunhas de vista, mas de oitiva; deu-se honesta pressa em mandar as novas para cá, tão minuciosas e graves, que chamaram naturalmente a atenção pública. Outras folhas também as deram; mas serão todas verdadeiras? Eis a questão. O número dos sequazes do Conselheiro sobe já a dez mil, não contando os lavradores e comerciantes que o ajudam com gêneros e dinheiros. </p>

<p>Dado que tudo seja exato, não basta para conhecer uma doutrina. Diz-se que é um místico, mas é tão fácil supô-lo que não adianta nada dizê-lo. Nenhum jornal mandou ninguém aos Canudos. Um repórter paciente e sagaz, meio fotógrafo ou desenhista, para trazer as feições do Conselheiro e dos principais sub-chefes, podia ia ao centro da seita nova e colher a verdade inteira sobre ela. Seria uma proeza americana. Seria uma empresa quase igual à remoção do Bendegó, que devemos ao esforço e direção de um patrício tenaz. Uma comissão não poderia ir; as comissões geralmente divergem logo na data da primeira conferência, e é duvidoso que esta desembarcasse na Bahia sem três opiniões (pelo menos) acerca do Joazeiro. </p>

<p>Não se sabendo a verdadeira doutrina da seita, resta-nos a imaginação para descobri-la e a poesia para floreá-la. Estas têm direitos anteriores a toda organização civil e política. A imaginação de Eva fê-la escutar sem nojo um animal tão imundo como a cobra, e a poesia de Adão é que o levou a amar aquela tonta que lhe fez perder o paraíso terrestre. </p>

<p>Que vínculo é esse, repito, que prende tão fortemente os fanáticos ao Conselheiro? Imaginação, cavalo de asas, sacode as crinas e dispara por aí fora; o espaço é infinito. Tu, poesia, trepa-lhe aos flancos, que o espaço, além de infinito, é azul. Ide, voai, em busca da estrela de ouro que se esconde além, e mostrai-nos em que é que consiste a doutrina deste homem. Não vos fieis no telegrama da Gazeta, que diz estarem com ele quatro classes de fanáticos, e só uma delas sincera. Primeiro que tudo, quase não há grupo a que se não agregue certo número de homens interessados e empulhadores; e, se vos contentais com uma velha chapa, a perfeição não é deste mundo. Depois, se há crentes verdadeiros, é que acreditam em alguma coisa. Essa coisa é que é o mistério. Tão atrativa é ela que um homem, não suspeito de conselheirista, foi com a senhora visitar o apóstolo, deixando-lhe de esmola quinhentos mil réis, e ela quatrocentos mil. Esta notícia é sintomática. Se um pai de família, capitalista ou fazendeiro, pega em si e na esposa e vai dar pelas próprias mãos algum auxílio pecuniário ao Conselheiro, que já possui uns cem contos de réis, é que a palavra deste passa além das fileiras de combate. </p>

<p>Não trato, porém, de conselheiristas ou não conselheiristas; trato do conselheirismo, e por causa dele é que protesto e torno a protestar contra a perseguição que se está fazendo à seita. Vamos perder um assunto vago, remoto, fecundo e pavoroso. Aquele homem, que reforça as trincheiras envenenando os rios, é um Maomé forrado de um Bórgia. Vede que acaba de despir o burel e o bastão pelas armas; a imagem do bastão e do burel dá-lhe um caráter hierático. Enfim, deve exercer uma fascinação grande para incutir a sua doutrina em uns e a esperança da riqueza em outros. Chego a imaginar que o elegem para a câmara dos deputados, e que ele aí chega, como aquele francês muçulmano, que ora figura na câmara de Paris, com turbante e burnu. Estou a ver entrar o Conselheiro, deixando o bastão onde outros deixam o guarda-chuva e sentando o burel onde outros pousam as calças. Estou a vê-lo erguer-se e propor indenização para os seus dez mil homens dos Canudos... </p>

<p>A perseguição faz-nos perder isto; acabará por derribar o apóstolo, destruir a seita e matar os fanáticos. A paz tornará ao sertão, e com ela a monotonia. A monotonia virá também à nossa alma. Que nos ficará depois da vitória da lei? A nossa memória, flor de quarenta e oito horas, não terá para regalo a água fresca da poesia e da imaginação, pois seria profaná-las com desastres elétricos de Santa Teresa, roubos, contrabandos e outras anedotas sucedidas nas quintas-feiras para se esquecerem nos sábados. </p>

<p>7 de fevereiro </p>

<p>A semana é de mulheres. Não falo daquelas finas damas elegantes que dançaram em Petrópolis por amor de uma obra de caridade. Para falar delas não faltarão nunca penas excelentes. Quisera dizer penas de alguma ave graciosa, a fim de emparelhar com a de à guia que vai servir para assinar o tratado de arbitramento entre os Estados Unidos e a Inglaterra. Mas se o nome de pena ficou ao pedacinho de metal que ora usamos, direi as damas de Petrópolis que também haverá um coração para adornar as que escreverem delas, como houve um para enfeitar a pena de águia diplomática. Diferem os dois corações em ser este de ouro, cravejado de brilhantes. E são ingleses! e são anglo-americanos! E dizem-se homens práticos e duros! Em meio de tanta dureza e tanta prática, lá acharam uma nesga azul de poesia, um raio de simbolismo e uma expressão de sentimento que se confunde com a dos namorados. </p>

<p>Nós, que não somos práticos e temos uma nota de meiguice no coração, tão alegres que enchemos as ruas de confetes cinco ou seis semanas antes do carnaval, nós não proporíamos aquele coração de ouro com brilhantes para assinar </p>

<p>o tratado. Não é porque as nossas finanças estão antes para o simples aço de Birmingham, mas por não cair em ternura pública, neste fim de século, e um pouco por medo da troca. Nós temos da seriedade uma idéia que se confunde com a de sequidão. Ministro que em tal pensasse cuidaria ouvir, alta noite, por baixo das janelas, ao som do violão, aqueles célebres versos de Laurindo: </p>

<p>Coração, por que palpitas?  
Coração, por que te agitas? 
</p>

<p>Os ingleses e os anglo-americanos, esses são capazes de achar uma nota de poesia nas mulheres de soldados que se foram despedir de seus amigos do 7º batalhão, quando este embarcou para a Bahia, quarta-feira. Foram despedir-se à praia, como as esposas dos Lusíadas e até as fizeram lembrar aos que não esqueceram este e os demais versos: “Qual em cabelo: Ó doce e amado esposo!” As diferenças são grandes; umas eram consortes dos barões assinalados que saíram a romper o mar “que geração alguma não abriu”, estas cá são tristes sócias dos soldados, e não podiam ir com eles, como de costume. Queriam acompanhá-los até a Bahia, até o sertão, até os Canudos, onde o Major Febrônio não entrou, por motivos constantes de um documento público. Dizem que choravam muitas; dizem que outras declaravam que iriam em breve juntar-se a eles, tendo vivido com eles e querendo morrer com eles. Delas não poucas os vieram acompanhando de Santa Catarina e nada conheciam da cidade, mas bradavam com a mesma alma que buscariam meios de chegar até onde chegasse a expedição. </p>

<p>Talvez tudo isso vos pareça reles e chato. Deus meu, não são as lástimas de Dido, nem a meia dúzia de linhas da notícia podem pedir meças aos versos do poeta. Os soldados do 7º batalhão não são Enéias; vão à cata de um iluminado e seus fanáticos, empresa menos para glória que para trabalhos duros. Assim é; mas é também certo, pelo que dizem as gazetas, que as tais mulheres padeciam deveras. Ora, a dor, por mais rasteira que doa, não perde o seu ofício de doer. Essas amigas de quartel não elevam o espírito, mas pode ser que contriste ouvi-las, como entristece ver as feridas dos mendigos que andam na rua ou residem nas calçadas, corredores e portas. </p>

<p>Entre parêntesis, não excluo do número dos mendigos aqueles mesmos que têm carro, porquanto as suas despesas são relativamente grandes. Há dias, alguém que lê os jornais de fio a pavio deu com um anúncio de um homem que se oferecia para puxar carro de mendigo; donde concluía esta senhora (é uma senhora) que há homens mais mendigos que os próprios mendigos. Chegou ao ponto de crer que a carreira do mendigo é próspera, uma vez que a dos seus criados é atrativa. Não vou tão longe; eu creio que antes ser diretor de banco, — ainda de banco que não pague dividendos. Tem outro asseio, outra compostura, outra respeitabilidade, e durante o exercício governa o mercado, ou faz que governa, que é a mesma coisa. </p>

<p>Pobres amigas de quartel! Não direi, para fazer poesia, que fostes misturar as vossas lágrimas amargas com o mar, que é também amargo; faria apenas um trocadilho, sem grande sentido, pois não é o sal que dói. Também não quero notar que a aflição é a rasoura da gala e do molambo. Não; eu sou mais humano; eu peço para vós uma esperança, — a esperança máxima, que é o esquecimento. Se não houverdes dinheiro para embarcar, pedi ao menos o esquecimento, e este caluniado amigo dos homens pode ser que venha sentar-se à beira das velhas tábuas que vos servem de leito. Se ele vier, não o mandeis embora; há casos em que ele não é preciso, e entretanto fica e faz prosperar um sentimento novo. No nosso pode ser necessário. Enquanto o sócio perde uma perna cumprindo o seu dever, a sócia deslembrada perde a saudade, que dói mais que ferro no corpo, e tudo se acomoda. </p>

<p>Lágrimas parecem-se com féretros. Quando algum destes passa, rico ou pobre, acompanhado ou sozinho, todos tiram o chapéu sem interromper a conversação, que tanto pode ser da expedição dos Canudos como do naufrágio da Laje. Por isso, descobre-te ao ver passar aquelas outras lágrimas humildes e desesperadas que verteram as esposas e filhos dos operários que naufragaram na fortaleza. Também estas correram à praia, umas pelos pais, outras pelos maridos, todas por defuntos, dos quais só alguns apareceram; a maior parte, se não ficou ali no seio das águas, foi levada por estas, barra fora, à descoberta de um mundo mais que velho. </p>

<p>Era uso dos operários irem às manhãs e tornarem às tardes; mas o mar tem surpresas, e as suas águas não amam só as vítimas ilustres. Também lhes servem as obscuras, sem que aliás precisem de umas nem de outras; mas é por amor dos homens que elas os matam. Assim ficam eles avisados a se não arriscarem mais sem grandes cautelas. </p>

<p>Em caso de desespero, não trabalhem. O trabalho é honesto, mas há outras ocupações pouco menos honestas e muito mais lucrativas. </p>

<p>14 de fevereiro </p>

<p>Conheci ontem o que é celebridade. Estava comprando gazetas a um homem que as vende na calçada da Rua de São José, esquina do Largo da Carioca, quando vi chegar uma mulher simples e dizer ao vendedor com voz descansada: </p>


<p>
—

 Me dá uma folha que traz o retrato desse homem que briga lá fora. 
</p>

<p>
—

 Quem? 
</p>

<p>
—

 Me esqueceu o nome dele. 
</p>


<p>Leitor obtuso, se não percebeste que “esse homem que briga lá fora” é nada menos que o nosso Antônio Conselheiro, crê-me que és ainda mais obtuso do que pareces. A mulher provavelmente não sabe ler, ouviu falar da seita dos Canudos, com muito pormenor misterioso, muita auréola, muita lenda, disseram-lhe que algum jornal dera o retrato do Messias do sertão, e foi comprá-lo, ignorando que nas ruas só se vendem as folhas do dia. Não sabe o nome do Messias; é “esse homem que briga lá fora”. A celebridade, caro e tapado leitor, é isto mesmo. O nome de Antônio Conselheiro acabará por entrar na memória desta mulher anônima, e não sairá mais. Ela levava uma pequena, naturalmente filha; um dia contará a história à filha, depois à neta, à porta da estalagem, ou no quarto em que residirem. </p>

<p>Esta é a celebridade. Outra prova é o eco de Nova Iorque e de Londres onde o nome de Antônio Conselheiro fez baixar os nossos fundos. O efeito é triste, mas vê se tu, leitor sem fanatismo, vê se és capaz de fazer baixar o menor dos nossos títulos. Habitante da cidade, podes ser conhecido de toda a Rua do Ouvidor e seus arrabaldes, cansar os chapéus, as mãos, as bocas dos outros em saudações e elogios; com tudo isso, com o teu nome nas folhas ou nas esquinas de uma rua, não chegarás ao poder daquele homenzinho, que passeia pelo sertão uma vila, uma pequena cidade, a que só falta uma folha, um teatro, um clube, uma polícia e sete ou oito roletas, para entrar nos almanaques. </p>

<p>Um dia, anos depois de extinta a seita e a gente dos Canudos, Coelho Neto, contador de coisas do sertão, talvez nos de algum quadro daquela vida, fazendo-se cronista imaginoso e magnífico deste episódio que não tem nada fim-de-século. Se leste o Sertão, primeiro livro da “Coleção Alva”, que ele nos deu agora, concordarás comigo. Coelho Neto ama o sertão, como já amou o Oriente, e tem na palheta as cores próprias — de cada paisagem. Possui o senso da vida exterior. Dá-nos a floresta, com os seus rumores e silêncios, com os seus bichos e rios, e pinta-nos um caboclo que, por menos que os olhos estejam acostumados a ele, reconhecerão que é um caboclo. </p>

<p>Este livro do Sertão tem as exuberâncias do estilo do autor, a minuciosidade das formas, das coisas e dos momentos, o numeroso rol das características de uma cena ou de um quadro. Não se contenta com duas pinceladas breves e fortes; o colorido é longo, vigoroso e paciente, recamado de frases como aquela do céu quente “donde caía uma paz cansada”, e de imagens como esta: “A vida banzeira, apenas alegrada pelo som da voz de Felicinha, de um timbre fresco e sonoro de mocidade, derivava como um rio lodoso e pesado de águas grossas, à beira do qual cantava uma ave jucunda.” A natureza está presente a tudo nestas páginas. Quando Cabiúna morre (“Cega”, 280) e estão a fazer-lhe o caixão, à noite, são as águas, é o farfalhar das ramas fora que vem consolar os tristes de casa pela perda daquele “esposo fecundante das veigas virgens, patrono humano da floração dos campos, reparador dos flagelos do sol e das borrascas”. “Cega” é uma das mais aprimoradas novelas do livro. “Praga” terá algures demasiado arrojo, mas compensa o que houver nela excessivo pela vibração extraordinária dos quadros. </p>

<p>Estes não são alegres nem graciosos, mas a gente orça ali pela natureza da praga, que é o cólera. Agora, se quereis a morte jovial, tendes Firmo, o vaqueiro, um octogenário que “não deixa cair um verso no chão”, e morre cantando e ouvindo cantar ao som da viola. “Os Velhos” foram dados aqui. “Tapera” saiu na Revista Brasileira. </p>

<p>Os costumes são rudes e simples, agora amorosos, agora trágicos, as falas adequadas às pessoas, e as idéias não sobem da cerebração natural do matuto. Histórias sertanejas dão acaso não sei que gosto de ir descansar, alguns dias, da polidez encantadora e alguma vez enganadora das cidades. Varela sabia o ritmo particular desse sentimento; Gonçalves Dias, com andar por essas Europas fora, também o conhecia; e, para só falar de um prosador e de um vivo, Taunay dá vontade de acompanhar o Dr. Cirino e Pereira por aquela longa estrada que vai de Sant’Ana de Paranaíba a Camapuama, até o leito da graciosa Nocência. Se achardes no Sertão muito sertão, lembrai-vos que ele é infinito, e a vida ali não tem esta variedade que não nos faz ver que as casas são as mesmas, e os homens não são outros. Os que parecem outros um dia é que estavam escondidos em si mesmos. </p>

<p>Ora bem, quando acabar esta seita dos Canudos, talvez haja nela um livro sobre o fanatismo sertanejo e a figura do Messias. Outro Coelho Neto, se tiver igual talento, pode dar-nos daqui a um século um capítulo interessante, estudando o fervor dos bárbaros e a preguiça dos civilizados, que os deixaram crescer tanto, quando era mais fácil tê-los dissolvido com uma patrulha, desde que o simples frade não fez nada. Quem sabe? Talvez então algum devoto, relíquia dos Canudos, celebre o centenário desta finada seita. </p>

<p>Para isso, basta celebrar o centenário da cabeleira do apóstolo, como agora, pelo que diz o Jornal do Comércio, comemoraram em Londres o centenário da invenção do chapéu alto. Chapéus e cabelos são amigos velhos. Foi a 15 de janeiro último. Não conhecendo a história deste complemento masculino, nada posso dizer das circunstâncias em que ele apareceu no dia 15 de janeiro de 1797. Ou foi exposto à venda naquela data, ou apontou na rua, ou algum membro do parlamento entrou com ele no recinto dos debates, à maneira britânica. Fosse como fosse, os ingleses celebraram esse dia histórico da chapelaria humana. Sabeis o que Macaulay disse da morte de um rei e da morte de um rato. Aplicando o conceito ao presente caso, direi que a concepção de um chapeleiro no ventre de sua mãe é, em absoluto, mais interessante que a fabricação de um chapéu; mas, hipótese haverá em que a fabricação de um chapéu seja mais interessante que a concepção do chapeleiro. Este não passará do chapéu comum e trabalhará para uma geração apenas; aquele será novo e ficará para muitas gerações. </p>

<p>Com efeito, lá vai um século, e ainda não acabou o chapéu alto. O chapéu baixo e </p>

<p>o chapéu mole fazem-lhe concorrência por todos os feitios, e, às vezes parecem vencê-lo. Um fazendeiro, vindo há muitos anos a esta capital, na semana em que certa chapelaria da Rua de São José abriu ao público as suas seis ou sete portas, ficou pasmado de vê-las todas, de alto a baixo, cobertas de chapéus compridos. Tempo depois, voltando e indo ver a casa, achou-lhe as mesmas seis ou sete portas cobertas de chapéus curtos. Cuidou que a vitória destes era decidida, mas sabeis que se enganou. O chapéu alto durará ainda e durará por muitas dúzias de anos. Quando ninguém já o trouxer de passeio ou de visita, servirá nas cerimônias públicas. Eu ainda alcancei o porteiro do Senado, nos dias de abertura e de encerramento da assembléia geral, vestindo calção, meia e capa de seda preta, sapato raso com fivela, e espadim à cinta. Por fim acabou o vestuário do porteiro. O mesmo sucederá ao chapéu alto; mas por enquanto há quem celebre o seu primeiro século de existência. Tem-se dito muito mal deste chapéu. Chamam-lhe cartola, chaminé, e não tarda canudo, para rebaixá-lo até a cabeleira hirsuta de Antônio Conselheiro. No Carnaval, muita gente o não tolera, e os mais audazes saem à rua de chapéu baixo, não tanto para poupar o alto, como para resguardar a cabeça, sem a qual não há chapéu alto nem baixo. </p>

<p>21 de fevereiro </p>

<p>Estou com inveja aos argentinos. Agora que os gregos surgem de toda parte para correr a Atenas, receber armamento e passar à Ilha de Creta, Buenos Aires dá 200 desses patriotas que aí vão lutar contra os otomanos. Nós, que devíamos dar 500, não damos nenhum. Certamente não os temos, ou tão raros são eles que melhor é irem pela calada. Conheci outrora um grego. Petrococchino, homem da praça, e conheci também a Aimée, uma francesa, que em nossa língua se traduzia por amada, tanto nos dicionários como nos corações. Era uma criaturinha do finado Alcazar, que nenhuma Turquia defendeu da Hélade. Ao contrário, os turcos fugiram e a bandeira helênica se desfraldou na Creta da Rua Uruguaiana... E daí é possível que nem mesmo este Petrococchino fosse grego. </p>

<p>Notório, como ele era, não os temos agora. Na lista da polícia, aparecem às vezes nomes de gregos, como de turcos, mas a gente que cultiva a planta noturna pode adorar a cruz e o crescente, não se bate por ele nem por ela. Eu quisera, entretanto, ver partir daqui, Rua do Ouvidor abaixo, uma falange bradando para ser entendida da terra os versos de Hugo: En Grèce! En Grèce! Lembras-te, não? Se és do meu tempo não esqueceste que tu e eu, quando expeitorávamos os primeiros versos que os rapazes trazem consigo, as Orientais contavam já trinta anos e mais. Mas era por elas que ainda aprendíamos poesia. Trazíamos de cor as páginas contemporâneas da revolução helênica, e do bravo Canaris, queimador de navios, e da batalha de Navarino, e da marcha turca, e de toda aquela ressurreição de um país meio antigo, meio cristão. En Grèce! cantava o poeta, pedindo que lhe selassem o cavalo e lhe dessem a espada, que queria partir já, já, contra os turcos; mas a lira mudava subitamente de tom, e o poeta perguntava a si mesmo quem era ele. Confessava então não ser mais que uma folha que o vento leva, nem amar outra coisa mais que as estrelas e a lua. Tão pouca coisa não era nos demais versos em que cantava os heróis gregos, mas Hugo lembrava-se de Byron... </p>

<p>Com efeito, Byron, armando-se para ir ao encontro do muçulmano, se teve o melancólico desfecho de 1824, nem por isso perdeu o brilhante arranco de 1823; era preciso fazer coisa idêntica ou análoga. Não se podia convidar a bater os turcos sem ir pelo mesmo caminho. Um poeta lírico tinha de ser efetivamente épico. E vede bem este grande homem, que ainda ontem Olavo Bilac evocava aqui, naquela prosa sugestiva que lhe conheces, vede bem que não estava aborrecido nem cansado: acabava de escrever os últimos cantos de Don Juan, e não sorvera ainda os últimos beijos da Guiccioli. Para levar alguma parte desta para a Grécia, levou-lhe o irmão, cunhado in partibus infidelium, e meteu-se em navio que fretou, com um médico e remédios para mil homens durante um ano. Na Grécia organizou e equipou umas centenas de soldados e pôs-se a testa deles. Nem todos poderiam fazer as coisas por este estilo grandioso. Era, ao mesmo tempo que um ato heróico, uma aventura poética, um apêndice do Child Harold. A febre não quis que ele perecesse na ponta de uma adaga otomana. Missolonghi avisou assim aos demais poetas que não saíssem a campo, em defesa da velha Grécia remoçada, não por medo de morrer ali ou alhures, mas porque o exemplo de Byron devia ficar com Byron. O epitáfio do poeta tinha de ser único. </p>

<p>Ao concerto universal daquele tempo não faltaram liras nem poetas. Cada língua teve o seu Píndaro. Lembra-te de Lamartine; lembra-te de José Bonifácio, cuja célebre ode clamava aos gregos, com entusiasmo: Sois helenos! sois homens! Compara ontem com hoje. Talvez o ardor do Romantismo ajudou a incendiar as almas. Os olhos estavam ainda mal acordados daquele vasto pesadelo imperial, que fora também um grande sonho, campanhas de conquista e de opressão, campanhas de liberdade, tudo feito, desfeito e refeito; a reconstituição da Grécia pedia uma cruzada particular. Cimódoce pergunta a Eudoro: “Há também uma Vênus cristã?” Esta Vênus era agora a própria Grécia convertida, como a heroína de Chateaubriand, e conquistada ao turco depois de muito sangue. </p>

<p>Que os helenos são homens é o que estás vendo agora, quando toda a faculdade de medicina internacional cuida de alongar os dias do “enfermo”, com os seus xaropes de notas e pílulas de esquadras sem fogo. Os ínfimos gregos não se arreceiam e, cansados de ouvir gemer Creta, lá se foram a arrancá-la dos braços otomanos. A diplomacia é uma bela arte, uma nobre e grande arte; o único defeito que há nas suas admiráveis teias de aranha é que uma bala fura tudo, e a vontade de um povo, se algum santo entusiasmo lhe aquece as veias, pode esfrangalhar as mais finas obras da astúcia humana. Se a Grécia acabar vencendo, as grandes potências não terão sido mais que jogadores de voltarete a tentos. </p>

<p>Que outra coisa têm sido elas, a propósito das reformas turcas? As reformas vêm, não vêm, redigem-se, emendam-se, copiam-se, propõem-se, aceitam-se, vão cumprir-se e não se cumprem. Vereis que ainda caem como as reformas cubanas, que, depois de tanto sangue derramado, vieram pálidas e mofinas. Ninguém as quer, e o ferro e o fogo continuam a velha obra. Assim se vai fazendo a história, com aparência igual ou vária, mediante a ação de leis, que nós pensamos emendar, quando temos a fortuna de vê-las. Muita vez não as vemos, e então imitamos Penélope e o seu tecido, desfazendo de noite o que fazemos de dia, enquanto outro tecelão maior, mais alto ou mais fundo e totalmente invisível compõe os fios de outra maneira, e com tal força que não podemos desfazer nada. Sucede que, passados tempos, o tecido esfarrapa-se e nós, que trabalhávamos em rompê-lo, cuidamos que a obra é nossa. Na verdade, a obra é nossa, mas é porque somos os dedos do tecelão; o desenho e o pensamento são dele, e presumindo empurrar a carroça, o animal é que a tira do atoleiro, um animal que somos nós mesmos... Mas aí me embrulho eu, e estou quase a perder-me em filosofias grossas e banais. Oh! banalíssimas! </p>

<p>Domingo próximo é possível que te explique esta confusão da minha alma. Estou certo que me entenderás e aplaudirás. Além da confusão da alma, imagina que me dói a testa em um só ponto escasso, no sobrolho direito; a dor, que não precisa de extensão grande para fazer padecer muito, contenta-se às vezes com o espaço necessário à cabeça de um alfinete. Também esta reflexão é banal, mas tem a vantagem de acabar a crônica. </p>

<p>28 de fevereiro </p>

<p>“Domingo próximo é possível que te explique esta confusão da minha alma. Estou certo que me entenderás e aplaudirás.” Assim concluí eu a Semana passada. Venho cumprir aquela meia promessa. </p>

<p>É certo que a festa suntuosa de quarta-feira afrouxou em parte a sensação exposta naquelas palavras. A recepção do palácio do governo respondeu ao que se esperava do ato, e deixou impressão forte e profunda. Aquele edifício que eu vi, há trinta anos, logo depois de acabado, passou por várias mãos, viveu na obscuridade e na hipoteca, passou finalmente ao poder do governo, e o ilustre Sr. Vice-presidente da República acaba de inaugurá-lo com raro esplendor. Foi o sucesso principal da semana; mas a semana já não é minha, como ides ver. </p>

<p>Leitor, Deus gastou seis dias em fazer este mundo, e repousou no sétimo. Ora, Deus podia muito bem não repousar, mas quis deixar um exemplo aos homens. Daí o nosso velho descanso de um dia, que os cristãos chamaram do Senhor. Eu não sou Deus, leitor; não criei este mundo, tanto que lhe acho algumas imperfeições, como a de nascerem as uvas verdes, para engano das raposas. Eu as faria nascer maduras e talvez já engarrafadas. Mas criticar obra feita não custa; Deus não podia prever que os homens não se limitassem a falsificar eleições e fizessem o mesmo ao vinho. </p>

<p>Vamos ao que importa. Se Deus descansou um dia, depois de seis dias de trabalho, força é que eu descanse algum tempo depois de uma obra de anos. Há cerca de cinco anos que vos digo aqui ao domingo o que me passa pela cabeça, a propósito da semana finda, e até sem nenhum propósito. Parece tempo de repousar o meu tanto. Que o repouso seja breve ou longo, é o que não sei dizer; vou estirar estes membros cansados e cochilar a minha sesta. </p>

<p>Antes de cochilar, podia fazer um exame de consciência e uma confissão pública, à maneira de Sarah Bernhardt ou de Santo Agostinho. Oh! perdoa-me, santo da minha devoção, perdoa esta união do teu nome com o da ilustre trágica; mas este século acabou por deitar todos os nomes no mesmo cesto, misturá-los, tirá-los sem ordem e cosê-los sem escolha. É um século fatigado. As Forças que despendeu, desde princípio, em aplaudir e odiar, foram enormes. Junta a isso as revoluções, as anexações, as dissoluções e as invenções de toda casta, políticas e filosóficas, artísticas e literárias, até as acrobáticas e farmacêuticas, e compreenderás que é um século esfalfado. Vive unicamente para não desmentir os almanaques. Todos os séculos têm cem anos; este não quer sair da velha regra, nem ser menos constante que o nosso robusto Barbacena, seu grande rival. Em lhe batendo a hora, irá com facilidade para onde foram os séculos de Péricles e de Augusto. </p>

<p>O meu exame de consciência, se houvesse de fazê-lo, não imitaria Agostinho nem Sarah. Nem tanta humildade, nem tanta glória. O grande santo dividiu, é verdade, as confissões humanas em duas ordens, uma que é um louvor, outra que é um gemido, definindo assim as suas e as da representante de Dona Sol. Faz crer que não há terceira classe, em que a gente possa louvar-se com moderação e gemer baixinho; mas eu cuido que há de haver. A imitar uma das duas, acho que a mais difícil seria a de Sarah. Não li ainda as confissões desta senhora, mas pela nota que nos deu dela Eça de Queirós, com aquela graça viva e cintilante dos seus três últimos “Bilhetes Postais”, não sei como é que uma criatura possa dizer tanta coisa de si mesma. Em particular, vá. Há pessoas que, não receando indiscretos, escancaram os corações, e os amigos reconhecem que, por mais que se pense bem de outro, pensa-se menos bem que ele próprio. Mas, em público, em letra de forma, no Fígaro, que é o Diário Oficial do universo, custa crer, mas é verdade. </p>

<p>Antes gemer, com esta cláusula de gemer baixinho, e confessar os pecados, mas com discrição e cautela. Pecados são ações, intenções ou omissões graves; não se devem contar todas, nem integralmente, mas só a parte que menos pesa à alma e não faz desmerecer uma pessoa no conceito dos homens. Não especifico, por não perder tempo, e quem se despede, mal pode dizer o essencial. O essencial aqui é dizer que não faço confissão alguma, nem do mal, nem do bem. Que mal me saiu da pena ou do coração? Fui antes pio e eqüitativo que rigoroso e injusto. Cheguei à elegia e à lágrima, e se não bebi todos os Cambarás e Jataís deste mundo, é porque espero encontrá-los no outro, onde já nos aguardam os xaropes do Bosque e de outras partes. Lá irá ter o grande Kneipp, e anos depois o kneippismo, pela regra de que primeiro morrem os autores que as invenções. Há mais de um exemplo na filosofia e na farmácia. </p>

<p>Não tireis da última frase a conclusão de ceticismo. Não achareis linha cética nestas minhas conversações dominicais. Se destes com alguma que se possa dizer pessimista, adverte que nada há mais oposto ao ceticismo. Achar que uma coisa é ruim, não é duvidar dela, mas afirmá-la. O verdadeiro cético não crê, como o Dr. Pangloss, que os narizes se fizeram para os óculos, nem, como eu, que os óculos é que se fizeram para os narizes; o cético verdadeiro descrê de uns e de outros. Que economia de vidros e de defluxos, se eu pudesse ter esta opinião! </p>

<p>Adeus, leitor. Força é deitar aqui o ponto final. A mim, se não fora a conveniência de ir para a rede, custar-me-ia muito pingar o dito ponto, pelas saudades que levo de ti. Não há nada como falar a uma pessoa que não interrompe. Diz-se-lhe tudo o que se quer, o que vale e o que não vale, repetem-se-lhe as coisas e os modos, as frases e as idéias, contradizem-se-lhe as opiniões, e a pessoa que lê, não interrompe. Pode lançar a folha para o lado ou acabar dormindo. Quem escreve não vê o gesto nem o sono, segue caminho e acaba. Verdade é que, neste momento, adivinho uma reflexão tua. Estás a pensar que o melhor modo de sair de uma obrigação destas não difere do de deixar um baile, que é descer ao vestiário, enfiar o sobretudo e sumir-se no carro ou na escuridão. Isto de empregar tanto discurso faz crer que se presumem saudades nos outros, além de ser fora da etiqueta. Tens razão, leitor; e, se fosse tempo de rasgar esta papelada e escrever diversamente, crê que o faria; mas é tarde, muito tarde. Demais, a frase final da outra semana precisava de ser explicada e cumprida; daí todos estes suspiros e curvaturas. Falei então na confusão da minha alma, e devia dizer em que é que ela consistia e consiste, e cuja era a causa. A causa está dita; é a natural melancolia da separação. Adeus, amigo, até a vista. Ou, se queres um jeito de falar mais nosso, até um dia. Creio que me entendeste, e creio também que me aplaudes, como te anunciei na semana passada. Adeus! </p>
   
           
                                
        </div>           
        <br />    <p class='text-center'> * * * </p>  <br /> <hr />  <br />            
          <div class="bg-info container-fluid col-xs-12">    <h5 class='text-center'>  Machado de Assis - Crônica - Links para os Livros    </h5>   </div> 
          <div class="text-center"><ul class="pagination pagination-lg">
          <!--  class="active"  -->
            <li   ><a href="Cronica-01">01</a></li>            
            <li   ><a href="Cronica-02">02</a></li>
            <li   ><a href="Cronica-03">03</a></li>
            <li   ><a href="Cronica-04">04</a></li>
            <li   ><a href="Cronica-05">05</a></li>
            <li   ><a href="Cronica-06">06</a></li>
            <li   ><a href="Cronica-07">07</a></li>
            <li   ><a href="Cronica-08">08</a></li>
            <li   ><a href="Cronica-09">09</a></li>
            <li   ><a href="Cronica-10">10</a></li>                                          
            <li   ><a href="Cronica-11">11</a></li>                                          
            <li   ><a href="Cronica-12">12</a></li>                                          
            <li   ><a href="Cronica-13">13</a></li>                                          
            <li   ><a href="Cronica-14">14</a></li>                                          
            <li   ><a href="Cronica-15">15</a></li>                                          
            <li   ><a href="Cronica-16">16</a></li>                                          
            <li class="active"  ><a href="Cronica-17">17</a></li>                                          
            <li   ><a href="Cronica-18">18</a></li>                                          
            <li   ><a href="Cronica-19">19</a></li>                                          
            <li   ><a href="Cronica-20">20</a></li>                                          
            <li   ><a href="Cronica-21">21</a></li>                                          
            <li   ><a href="Cronica-22">22</a></li>                                          
            <li   ><a href="Cronica-23">23</a></li>                                          
            <li   ><a href="Cronica-24">24</a></li>                                          
            <li   ><a href="Cronica-25">25</a></li>                                          
            <li   ><a href="Cronica-26">26</a></li>                                          
            <li   ><a href="Cronica-27">27</a></li>                                          
            <li   ><a href="Cronica-28">28</a></li>   
            <li   ><a href="Cronica-29">29</a></li>   
            <li   ><a href="Cronica-30">30</a></li>                 
          </ul>
        </div>
      </div>                   
</asp:Content>