<%@ Page Title="Wikipedia -     " Language="C#" MasterPageFile="~/PT/SitePTMachado.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content="      " /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>            
            <br />
            <h1>  Machado de Assis - Biografia	</h1>
            <br />
              <!-- INICIO - VIDEO do YOUTUBE
              <div class="embed-responsive embed-responsive-16by9">
               <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/" frameborder="0" allowfullscreen></iframe>
              </div>  <br /><br /><br />   <br /><br /><br />      
               FIM - VIDEO do YOUTUBE  -->            
        </div> 
      
      <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
         <br /> <h2 class='text-center'> Reputação crítica </h2>        <br /> 
                        
                   


<p>Machado usufruiu de grande prestígio em vida, fato raro para um escritor na época. Desde cedo ganhou reconhecimento de Antônio de Almeida e José de Alencar, que liam-no através de suas crônicas e contos nas revistas e jornais cariocas. Em 1881, com a publicação de Memórias Póstumas..., Urbano Duarte escreveu que sua obra era "falsa, deficiente, sem nitidez, e sem colorido." Com o impacto inovador do volume, Capistrano de Abreu questionava se o livro era mesmo um romance, ao passo que um outro comentarista chamava-lhe "sem correspondência nas literaturas de ambos os países de língua portuguesa".</p>
<p>Em 1908, a publicação de História da Literatura Brasileira, de José Veríssimo, intensificou esta última perspectiva crítica posicionando Machado de Assis como o cume da literatura nacional. Veríssimo entrou em conflito intelectual com Sílvio Romero, que também atribuía a Machado o título de maior escritor brasileiro, embora não notasse em seu trabalho uma maior expressividade. </p>
<p>O Brasil do fim do século XIX e o Brasil no início do século XX eram precários nos meios gráficos e de difusão, todavia seus livros alcançaram distantes regiões do país: na primeira metade do século XX, intelectuais e escritores do Mato Grosso já liam Machado e apoiavam-se em seu estilo como grande influência estética. Os modernistas de 22, contudo, consideravam-no "artificioso, sem vida e fora da realidade cotidiana". Mário de Andrade escreveu que, embora tenha produzido "apaixonante obra e do mais alto valor artístico", detestaria tê-lo por perto. Enquanto Astrojildo Pereira preconizava o "nacionalismo" em Machado, Octávio Brandão criticava a falta do socialismo científico em sua obra. Desta época, destaca-se também a crítica de Augusto Meyer, para quem o uso do homem subterrâneo na obra machadiana é um meio em que ele teria encontrado para relativizar todas as certezas.</p>
<p>A revolução modernista durante o começo e o meio do século vinte aproveitou a obra de Machado em objetivos da vanguarda. Ela foi alvo de feministas da década de 1970, como Helen Caldwell, que enxergou a personagem feminina Capitu de Dom Casmurro como vítima das palavras do narrador-homem, mudando completamente a perspectiva que se tinha até então deste romance. Antonio Candido escreveu que a erudição, a elegância e o estilo vazada numa linguagem castiça contribuíram para a popularidade de Machado de Assis. Com estudos da sexualidade e a psique humana, bem como com o surgimento do existencialismo, atribuiu-se um certo psicologismo às suas obras, especialmente "O Alienista", muitas vezes comparando-as com as de Freud e Sartre. A partir dos anos 80 e seguinte, a obra machadiana ficou amplamente aberta para movimentos como a psicanálise, filosofia, relativismo e teoria literária, comprovando que é aberta a diversas interpretações e que nos últimos tempos tem crescido um grande interesse em sua obra.</p>
<p>Nos últimos tempos, com recentes traduções para outras línguas, Machado de Assis tem sido considerado, por críticos e artistas do mundo inteiro, um "gênio injustamente relegado à negligência mundial". Harold Bloom o posicionou entre os 100 maiores gênios da literatura universal e "o maior literato negro surgido até o presente". Sua obra tem sido estudada hoje em dia por críticos do mundo inteiro, tais como Helen Caldwell (Estados Unidos), John Gledson (Inglaterra), Anatole France (França), David Jackson (Estados Unidos), Victor Orban (França), Samuel Putnam (Estados Unidos), Edith Fowke (Canadá), Susan Sontag (Estados Unidos) e outros, além de no Brasil serem conhecidos os nomes de Afrânio Coutinho, Alfredo Bosi, Lúcia Miguel Pereira, Roberto Schwarz, Raimundo Faoro, etc. A crítica moderna confere a Machado de Assis o título de melhor escritor brasileiro de todos os tempos, e sua obra é vista hoje em dia de fundamental importância para as universidades e a vida acadêmica em geral no país.</p>

 <br /> <hr /><br />          
       <h2 class='text-center'> Leituras   </h2>        <br />    


<p>Machado de Assis era um exímio leitor e, consecutivamente, sua obra foi influenciada pelas leituras que fazia. Após sua morte, seu patrimônio constituía, entre outras coisas, de aproximadamente 600 volumes encadernados, 400 em brochura e 400 folhetos e fascículos, no total de 1.400 peças. Sabe-se que era familiarizado com os textos clássicos e com a Bíblia. Em O Analista, Machado faz ligação à sátira menipeia clássica ao retomar a ironia e a paródia em Horário e Sêneca. O Eclesiastes, por sua vez, legou a Machado uma peculiar visão de mundo e foi seu livro de cabeceira no fim da vida.</p>
<p>Dom Casmurro é provavelmente a obra que mais possui influência teológica. Há referências a São Tiago e São Pedro, principalmente pelo fato de o narrador Bentinho ter estudado em seminário. Além disso, no Capítulo XVII Machado faz alusão a um oráculo pagão do mito de Aquiles e a ao pensamento israelita. De fato, Machado dispunha de uma biblioteca abastecida com teologia: crítica histórica sobre religião, à vida de Jesus, ao desenvolvimento do cristianismo, à literatura hebraica, à história Muçulmana, aos sistemas religiosos e filosóficos da Índia. Jean-Michel Massa realizou um catálogo dos livros da biblioteca do autor, que foi revisto em 2000 pela pesquisadora Glória Vianna, que constatou que 42 dos volumes da lista original de Massa estavam extraviados:</p>
 <br />
<ol>
<li>Les déicides: examen de la vie de Jésus et des développements de l´église chrétienne dans leurs rapports avec le judaïsme, de J. COHEN (1864).</li>
<li> La science des religions, de Emile Burnouf (1872).</li>
<li> Philosophie du droit ecclésiastique: des rapports de la religion et de l´État, de Adolphe Franck (1864).</li>
<li> Le pape et le concile, de Janus (1864).</li>
<li> L´Immaculée Conception - études sur l´origine d´un dogme, de A. Stap (1869).</li>
<li> Histoire littéraire de l´Ancien Testament, de Theodor Nöldeke (1873).</li>
<li> Historie du Mahométisme, de Charles Mills (1825).</li>
<li> Chants populaires du sud de l´Inde, sem o nome do autor (1868).</li>
<li> Pensées de Pascal (précédées de sa vie, par Madame Périer), de Blaise Pascal.</li>
<li> A Bíblia, contendo o Velho Testamento e o Novo Testamento, traduzida em português por António Pereira de Figueiredo, segundo a Vulgata Latina (1866).</li>
    </ol>
           <br />
<p>Machado também lia seus contemporâneos; admirava o realismo "sadio" e "colorido" de Manuel Antônio de Almeida e a "vocação analítica" de José de Alencar. Ele também leu Octave Feuillet, Gustave Flaubert, Balzac e Zola, mas sua maior influência advém da literatura inglesa, sobretudo Sterne e Jonathan Swift. Adepto do romance da Era vitoriana, era oposto à libertinagem literária do século anterior e vinculado às litotes no vocabulário e no desenvolvimento narrativo. </p>
<p>Sua obra também possui uma variedade de citações e correlações com quase todas de Shakespeare, notavelmente Otelo, Hamlet, Macbeth, Romeu e Julieta, O Estupro de Lucrécia e Como Gostais. Os escritores Sterne, Xavier de Maistre e Garret constituem a gama de autores que mais influenciaram a obra madura de Machado, sobretudo os capítulos 55 e 139 pontilhados, ou os capítulos-relâmpago (como 102,107,132 ou 136) e o garrancho da assinatura de Virgília no capítulo 142 das Memórias Póstumas de Brás Cubas. </p>
<p>Suas maiores influências na sátira e na forma narrativa livre, contudo, não advém da Inglaterra — mas da França. A "maneira livre" que Machado se refere nas linhas iniciais deste romance é uma afirmação explícita de Maistre, que lhe legou uma "narrativa caprichosa, digressiva, que vai e vem, sai da estrada para tomar atalhos, cultiva o a- propósito, apaga a linha reta, suprime conexões". De fato, Viagem à Roda do Meu Quarto (1794) fez com que Machado optasse por capítulos mais curtos do que aqueles produzidos em seu primeiro ciclo literário.</p>
<p>Outros estudiosos também citam o nome de filósofos, como Montaigne, Pascal e Schopenhauer. Este primeiro, com seus Essais (1580), apresentou a Machado a concepção do "homem diante das coisas" e despertou a repulsa de Machado de Assis à increpação de materialismo. Pascal, por sua vez, era leitura necessária à Machado, como ele próprio escreveu numa de suas cartas ao colega Joaquim Nabuco. Sérgio Buarque de Hollanda escreveu uma comparação da obra dos dois autores na seguinte forma: "Comparado ao de Pascal, o mundo de Machado de Assis é um mundo sem Paraíso. De onde uma insensibilidade incurável a todas as explicações que baseiam no pecado e na queda a ordem em que foram postas as coisas no mundo. Seu amoralismo tem raízes nessa insensibilidade fundamental." </p>
<p>E, por fim, Schopenhauer, onde, escrevem, Machado teria encontrado visões do pessimismo e ainda desdobrado sua escrita em mitos e metáforas acerca de uma "inexorabilidade do destino". Raimundo Faoro, sobre a obra do filósofo alemão na obra de Machado, argumentou que o autor brasileiro havia realizado uma "tradução machadiana da vontade de Schopenhauer" e que logrou conceber seu primeiro romance após "haver descoberto o fundamento metafísico do mundo, o demonismo da vontade que guia, sem meta nem destino, todas as coisas e os fantoches de carne e sangue." O mundo como vontade e representação (1819), para alguns, encontra seu cume alto em Machado de Assis com os desejos frustrados do personagem Brás Cubas.</p>

 <br /> <hr /><br />          
       <h2 class='text-center'> Influência   </h2>        <br />  



<p>Machado influenciou nomes como Olavo Bilac e Coelho Neto, Joaquim Francisco de Assis Brasil, Cyro dos Anjos, Lima Barreto (especialmente seu Triste Fim de Policarpo Quaresma), Moacir Scliar, Múcio Leão, Leo Vaz, Drummond de Andrade, Nélida Piñon, e sua obra permanece como uma das mais respeitadas e influentes da literatura brasileira. </p>
<p>Rubem Fonseca escreveu os contos "Chegou o Outono", "Noturno de Bordo" e "Mistura" baseado na linguagem de Machado de Assis— "a frase curta, despojada de ornatos, na emoção disfarçada, na reticência que sugere." Os temas teológicos abordados em seus contos, como em "Missa do Galo", influenciaram o escritor e pensador cristão Gustavo Corção. Lygia Fagundes Telles também se diz influenciada por Machado, especialmente por sua "ambiguidade, o texto enxuto, a análise social e a ironia fina". Em 1967, Lygia realizou a adaptação cinematográfica do romance Dom Casmurro com Paulo Emílio Sales Gomes, intitulado Capitu, com direção de Paulo Cesar Saraceni. Em 2006, Yasmin Jamil Nadaf realizou uma pesquisa que se concretizou no livro Machado de Assis em Mato Grosso: textos críticos da primeira metade do século XX, onde reúne nove textos de mato grossenses que já na época de Machado sofriam sua influência estética, dois desses escritos por José de Mesquita.</p>
<p>Sua obra também atinge a literatura estrangeira. Autores como John Barth e Donald Barthelme anunciaram terem sido influenciados por ele. A Ópera Flutuante, escrito pelo primeiro dos dois, foi influenciado pela técnica de "jogar livremente com as ideias" de Tristram Shandy e de Memórias Póstumas de Brás Cubas. O mesmo romance de Barth foi comparado por David Morrell com Dom Casmurro, onde ambos os personagens principais dos dois livros são advogados, chegam a pensar em suicídio e a comparar a vida a uma ópera, e vivem transtornados num triângulo amoroso. Isaac Goldberg traduziu o poema "Viver" para o inglês e sofreu influência de Machado em sua obra; sua visão de mundo pode ser comparada com a mesma visão de que tinha Machado de Assis. Susan Sontag, por sua vez, recebeu direta influência machadiana logo em seu primeiro romance. </p>
<p>Em 2011, ao ser entrevistado por The Guardian, Woody Allen listou Memórias Póstumas de Brás Cubas como um dos cinco livros que mais impactaram em sua vida como cineasta e escritor cômico.</p>
<p>Alguns estudiosos contemporâneos, especialmente Roberto Schwarz, o posicionam como um pré-modernista que prefigurou muitos dos estilos que culminariam na Semana de Arte Moderna. Em Grande Sertão: Veredas, Guimarães Rosa retoma a "viagem de memória" presente em Dom Casmurro e Memórias Póstumas de Brás Cubas, além de seus textos descreverem doenças mentais como os de Machado. </p>
<p>A produção modernista do século passado encontrou afinidades com a sua obra e, portanto, lançou relações entre Machado de Assis e nomes como Antonio Candido e Haroldo de Campos. Jô Soares é um dos escritores de hoje em dia que se diz influenciado por Machado, principalmente em seu Assassinatos na Academia Brasileira de Letras (2005). Milton Hatoum, também, tem em Machado uma de suas maiores influências. Seu mais famoso romance, Dois Irmãos (2000), é considerado um "diálogo aberto" com Esaú e Jacó. Recentemente, contos como "A Cartomante" e "O Alienista" foram revertidos em formato de quadrinhos e romances como Helena em mangá, mostrando que a obra machadiana continua vigorosa em novas mídias.</p>
 <br /> <hr /><br />          
       <h2 class='text-center'> Legado   </h2>        <br />  



<p>Álvares de Azevedo e Bernardo Guimarães já escreviam contos em meados do século XIX, mas os críticos notam que é com Machado que o gênero atinge novas possibilidades. Uma dessas possibilidades seria a de inaugurar, em livros como Contos Fluminenses (1870), Histórias da Meia-Noite (1873) e Papéis Avulsos (1882), "uma nova perspectiva estilística e uma nova visão da realidade, mais complexa e matizada." Esses livros trazem contos como "O Alienista", "Teoria do Medalhão" , "O Espelho", etc., em que aborda o poder, as instituições e também a loucura e a homossexualidade, que seriam temas literários muito precoces para a época. No gênero romance, com Dom Casmurro (1899), por exemplo, traria à tona uma intertextualidade e uma metalinguagem inovadoras na literatura e também muito influentes no futuro.</p>
<p>A Mocidade Independente de Padre Miguel homenageou a vida e obra de Machado de Assis no carnaval de 2009. Em 2006, Luís Antônio Giron escreveu que Machado de Assis "legou uma herança crítica que salva o Brasil do excesso de ufanismo nacionalista". Em 1868, José de Alencar chamaria Machado de "o primeiro crítico brasileiro." Além de ter sido um dos idealizadores da Academia Brasileira de Letras, Machado de Assis animou com suas crônicas e ideias políticas a Revista Brasileira, promoveu os poetas do Parnasianismo e estreitou relações com os maiores intelectuais de seu tempo, de José Veríssimo a Nabuco, de Taunay a Graça Aranha. De qualquer modo, existiria uma certa "riqueza mental" e "beleza moral" que Machado teria legado aos escritores no Brasil, e de fato alguns autores escrevem que "Machado de Assis é fundamental para quem quer escrever."</p>
<p>Muitos o consideram um grande predecessor: não bastasse ter introduzido o "realismo" na literatura nacional, certos críticos, como Roberto Schwarz, dizem que ele diz "coisas que Freud diria 25 anos depois". Em Esaú e Jacó, por exemplo, teria antecipado o conceito freudiano de 'complexo de Édipo’". </p>
<p>Em Dom Casmurro, teria escrito coisas, principalmente em relação à correlação entre sonho e vigília, que antecipariam a Interpretação dos Sonhos, publicado no mesmo ano que este livro. Críticos estrangeiros referem-se que ele também precedeu, com Memórias Póstumas de Brás Cubas (1881) e "O Espelho" (1882), as ficções fantásticas do realismo mágico de escritores como Jorge Luis Borges e Julio Cortázar, e também o Modernismo, através de intromissões no enredo dos romances e pela opção de capítulos curtos. </p>
<p>Enfim, como escreve Antonio Candido, embora tenha escrito e vivido mais no século XIX, podemos encontrar na ficção machadiana "disfarçados por curiosos traços arcaizantes, alguns dos temas que seriam característicos da ficção do século XX."</p>
<p>Além disso tudo, a obra machadiana é de fundamental importância para a análise das transições políticas no Brasil e da sociedade do Rio de Janeiro do século XIX e século XX, desde sua moda, transportes, arquiteturas e agitações financeiras. Sua obra—não só romances mas também as crônicas—exerce um papel importante para o conhecimento do Segundo Reinado no Brasil e inícios da República. Do ponto de vista universal, sua genialidade é vista como resultado de consistentes razões por demonstrar que seu trabalho, elogiado como é, não encontrou precedentes e, mesmo depois de mais de um século de intensa produção artística no Brasil, são obras citadas como das mais relevantes e mais geniais da classe literária do país. Além disso, segundo escrevem Benedito Antunes e Sérgio Vicente Motta,"[...] há um universalismo que Machado legou à nossa literatura e uma projeção de nossa literatura à esfera internacional, ao construir uma arte ao mesmo tempo brasileira e universal. </p>
<p>Portanto, a invenção machadiana já pressupunha 'caminhos cruzados'."</p>
<p>O seu nome consta da lista de colaboradores da Revista Contemporânea de Portugal e Brasil (1859-1865).</p>
    
            



		    
     </div> <div>    <br /> <br />  <br />   <p class='text-center'> * * * </p>  <br /> <hr />  <br />  <br />      <br />         </div>                      
     

      </div>                   
</asp:Content>