<%@ Page Title="Wikipedia -     " Language="C#" MasterPageFile="~/PT/SitePTMachado.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content="      " /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>            
            <br />
            <h1>  Machado de Assis - Biografia	</h1>
            <br />
              <!-- INICIO - VIDEO do YOUTUBE
              <div class="embed-responsive embed-responsive-16by9">
               <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/" frameborder="0" allowfullscreen></iframe>
              </div>  <br /><br /><br />   <br /><br /><br />      
               FIM - VIDEO do YOUTUBE  -->            
        </div> 
      
      <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
         <br /> <h2 class='text-center'> Especulações sobre Machado </h2>        <br /> 
                        
            



 <br /> <h2 class='text-center'> Política </h2>        <br /> 



<p> Machado de Assis pôde assistir, ao longo do século XIX e no começo do século XX, a alterações vastas e decisivas no cenário internacional e nacional, nos costumes, nas ciências da natureza e da sociedade, nas técnicas e em tudo o que entende com o progresso material. Alguns estudiosos supõem, no entanto, que as crenças atribuídas a Machado de Assis como um escritor engajado são falsas e que ele não esperava nada ou quase nada da história e da política.</p>
<p>Por exemplo: quanto às guerras e os conflitos políticos de sua época, dá de ombros, ao escrever: "Guerras africanas, rebeliões asiáticas, queda do gabinete francês, agitação política, a proposta de supressão do senado, a caixa do Egito, o socialismo, a anarquia, a crise europeia, que faz estremecer o solo, e só não explode porque a natureza, minha amiga, aborrece este verbo, mas há de estourar, com certeza, antes do fim do século, que me importa tudo isso? Que me importa que, na ilha de Creta, cristãos e muçulmanos se matem uns aos outros, segundo dizem telegramas de 25? E o acordo, que anteontem estava feito entre chilenos e argentinos, e já ontem deixou de estar feito, que tenho eu com esse sangue e com o que há de correr?"</p>
<p>Por outro lado, Machado foi um grande comentador dos casos que ocorriam com os políticos do país. Suas crônicas estão repletas destes comentários. Em 1868, por exemplo, D. Pedro II demitiu o gabinete liberal de Zacarias de Góis e substitui-o pelo gabinete conservador de Itaboraí. Grêmios e jornais liberais acusaram a atitude do imperador de bonapartista. Machado testemunhou o ato com simpatia aos liberais; de fato, era essa a sua "cor ideológica" ao longo dos anos 60. Em 1895, ao noticiar a morte de Joaquim Saldanha Marinho, liberal, maçom e republicano, Machado escreveu: "Os liberais voltaram mais tarde, tornaram a sair e a voltar, até que se foram devez, como os conservadores, e com uns e outros o Império." Sabe-se, também, que Machado era fervorosamente contra a escravidão. </p>
<p>Em 1888, com a abolição da escravatura, sai às ruas em carruagem aberta, como escreveu numa crônica de A Semana: "Houve sol, e grande sol, naquele domingo de 1888, em que o Senado votou a lei, que a regente [ Princesa Isabel ] sancionou, e todos saímos à rua. Sim, também eu saí à rua, eu o mais encolhido dos caramujos, também eu entrei no préstito, em carruagem aberta (...) Verdadeiramente, foi o único dia de delírio que me lembra ter visto."</p>
<p>Em crônica de 22 de julho de 1894, intitulada "Canção de Piratas", também refere-se à Guerra de Canudos (1896-1897), apoiando Antonio Conselheiro de Canudos por seus legionários se indignarem com a realidade clichê e tediante da época, e escreve: "Jornais e telegramas dizem dos clavinoteiros e dos sequazes do Conselheiro que são criminosos; nem outra palavra pode sair de cérebros alinhados, registrados, qualificados, cérebros eleitores e contribuintes. Para nós, artistas, é a renascença, é um raio de sol que, através da chuva miúda e aborrecida, vem dourar-nos a janela e a alma. É a poesia que nos levanta do meio da prosa chilra e dura deste fim de século."</p>
<p>Fundou em 1860 com seu cunhado Josefino Vieira o periódico O Jequitinhonha, por meio do qual teria difundido o ideal republicano. No entanto, a República trouxe muitos desagrados a ele. Com o fim do Império, o jornalismo começou a dar mais atenção à companhias, aos bancos e à Bolsa do que à arena parlamentar. Neste breve período, o capitalismo brasileiro, mediado pelo Estado, "ensaiava temerariamente os primeiros passos no regime nascente", como escreveu Raimundo Faoro. Sabe-se que Machado detestava o "vale-tudo do dinheiro pelo dinheiro". Em crônica de 18, escreveu: "Prisões, que tenho eu com elas? Processos, que tenho eu com eles? Não dirijo companhia alguma, nem anônima, nem pseudônima; não fundei bancos, nem me disponho a fundá-los; e, de todas as coisas deste mundo e do outro, a que menos entendo, é o câmbio. (...) Finanças, finanças, são tudo finanças."</p>
<p>Machado acreditava que o sonho poético de outrora estava se desfazendo com a modernização política. E, de certa forma, ele mesmo se desfazia: em 1900, envia uma carta a um colega discutindo se o que aparecia naquele determinado momento eram os "pés" do século XIX ou se já era a "cabeça" do século XX e ele afirma: "eu sou pela cabeça", ou seja, "meu século já acabou". Alfredo Bosi escreveu que o autor não via maus ou bons resultados na mudança do "despotismo milenar" ao "liberalismo dos reformadores turcos", mas que a "beleza da tradição" [ monárquica ] sucumbia à "força das mudanças ideológicas". Para Machado de Assis, enfim, tudo tinha sua mudança. Em crônica do dia 16 de junho de 1878, escreveu: "Os dias passam, e os meses, e os anos, e as situações políticas, e as gerações, e os sentimentos, e as ideias."</p>

 <br /> <hr /><br />          
       <h2 class='text-center'> Religião   </h2>        <br />    


<p>Tem-se intensificado a tentativa de descobrir a religião de Machado de Assis. Sabe-se que na infância ajudava uma igreja local e que fora parcialmente educado em idiomas por um padre, o já citado Silveira Sarmento. Analisando sua obra, muitos críticos o colocaram ao lado de Otávio Brandão, crendo que ele era adepto absoluto do niilismo. Outros o enxergavam como um perfeito ateu, no entanto recebeu profunda influência de textos católicos. De fato, a religião de Machado de Assis tornou-se tão obscura que talvez não haja outro método senão procurá-la em sua obra.</p>
<p>Como poeta, escreveu três poemas correlacionados no que se refere à orações e ao antagonismo entre a Roma antiga, o Paganismo e a Cristandade: "Fé", "O Dilúvio" e "Visão", as duas primeiras publicadas em Crisálidas (1864) e a última em Falenas (1870). Alguns especialistas notam nestes três poemas que Machado vangloriava a fé e a grandeza de Deus, mas num sentido mais poético e renascentista que doutrinário ou moralista. </p>
<p>Autores como Hugo Bressane de Araújo analisaram sua obra sob aspecto exclusivamente religioso, citando muito embora os dizeres de Machado ser "anti-clerical"; contudo, a mentalidade de Araújo limita-se a um pensamento religioso e não crítico literário, por ter sido bispo diocesano. Em Memórias Póstumas de Brás Cubas, há uma passagem em que Quincas Borba diz: "O Humanitismo há de ser também uma religião, a do futuro, a única verdadeira. </p>
<p>O cristianismo é bom para as mulheres e os mendigos, e as outras religiões não valem mais do que essa: orçam todas pela mesma vulgaridade ou fraqueza. O paraíso cristão é um digno êmulo do paraíso muçulmano; e quanto ao nirvana de Buda não passa de uma concepção de paralíticos. Verás o que é a religião humanística. A absorção final, a fase contrativa, é a reconstituição da substância, não o seu aniquilamento, etc." Entretanto, tal trecho não passa da fala de uma personagem fictícia, em que Quincas Borba tenta elevar sua própria religião, e mesmo o Humanitismo é apenas uma das invenções irônicas de Machado de Assis; Candido escreveu que a essência da crítica machadiana é "a transformação do homem em objeto do homem, que é uma das maldições ligadas à falta de liberdade verdadeira, econômica e espiritual."</p>
<p>Para entenderem mais a fundo suas convicções pessoais, os críticos analisam as crônicas publicadas nos jornais para entenderem melhor seu real pensamento. Em "Canção de Piratas", publicada na Gazeta de Notícias em 22 de julho de 1894, apoia Antonio Conselheiro de Canudos por seus legionários se indignarem com a realidade clichê e tediante da época, e critica os métodos da Igreja: "O próprio amor é regulado por lei; os consórcios celebram-se por um regulamento em casa do pretor, e por um ritual na casa de Deus, tudo com a etiqueta dos carros e casacas, palavras simbólicas, gestos de convenção."</p>
<p>Além disso, no Rio de Janeiro de sua época, também sabe-se que o Espiritismo crescia expressivamente. Numa suposta visita à Federação Espírita Brasileira, escrevera numa crônica na Gazeta de Notícias do dia 5 de outubro de 1885 onde relata uma suposta viagem astral que tivera. Embora tenham surgido análises afirmando que Memórias Póstumas de Brás Cubas fosse um livro cujo estilo era influenciado pelo conceito de "psicografia", críticos modernos acreditam que Machado encarava a religião espírita como todo movimento novo que possui a pretensão de se apresentar como solução dos males "não resolvidos" pelos seres humanos.</p>
<br /> <hr /><br />          
       <h2 class='text-center'> Saúde   </h2>        <br />    



<p>Para biógrafos ortodoxos, Machado de Assis possuía uma saúde muito frágil; acredita-se que tenha nascido com epilepsia e gagueira, e que desenvolveu ao longo de sua vida problemas nervosos, cegueira, depressão, e que teriam se agravado de após o falecimento da esposa. As crises epilépticas teriam se iniciado na infância, tendo remissão na adolescência e recidivaram na terceira década, tornando-se mais frequentes nos últimos anos. </p>
<p>Disfarçando a gagueira, conta-se que certa vez lhe notaram a dificuldade com que se expressava por conta das mordeduras na língua, ao que o escritor retrucou: "estas aftas, estas aftas..." Quanto à epilepsia, crê-se que não a contou nem mesmo para Carolina antes do casamento até acometê-lo uma crise generalizada tônico-clônica que desde criança prefigurava como "umas coisas esquisitas" que não haviam se repetido até o casamento. Crê-se que o autor não tivesse tido até então uma crise típica. Mesmo antes da morte de Carolina, em 1880 parcialmente perdeu a visão, tendo que ouvir a esposa ler-lhe textos de jornais ou livros.</p>
<p>Certos biógrafos dizem que ele não aludia sua enfermidade e nem lhe escrevia o nome, como em sua correspondência com o amigo Mário de Alencar: "O muito trabalhar destes últimos dias tem-me trazido alguns fenômenos nervosos..." Para alguns, a censura da palavra "epilepsia" lhe fez excluí-la das edições ulteriores de Memórias Póstumas de Brás Cubas, mas que deixaria escapar na edição primeira ao descrever o padecimento da personagem Virgília diante da morte do amante: Não digo que se carpisse; não digo que se deixasse rolar pelo chão, epiléptica..., que fora substituída por: Não digo que se carpisse, não digo que se deixasse rolar pelo chão, convulsa...</p>
<p>Praticamente todos seus biógrafos fizeram o diagnóstico de epilepsia: Lopes (1981) sugeriu a ocorrência, muito comum pelo menos na última fase da vida, de crises psicomotoras, provavelmente decorrentes de foco temporal e da ínsula, enquanto Guerreiro (1992), utilizando conceitos da epileptologia atual, assinalou que sofria alterações da consciência, automatismos e confusão pós-crítica. Ambos autores chegaram à conclusão que as crises eram provenientes do lobo temporal direito. Alguns indicam que um complexo de inferioridade acrescido de um grande introvertimento contribuíram para sua personalidade epileptóide. Segundo A. Botelho, "o epiléptico nem sempre está irritado, porém se mostra com frequência apático, deprimido e triste, com plena consciência de sua inferioridade social." A epilepsia seria, definitivamente, um fardo para Machado. </p>
<p>Carlos de Laet presenciou o que seria uma de suas crises públicas e descreveu-a assim: "Estava eu a conversar com alguém na Rua Gonçalves Dias, quando de nós se acercou o Machado e dirigiu-me palavras em que não percebi nexo. Encarei-o surpreso e achei-lhe desmudada a fisionomia. Sabendo que de tempos em tempos o salteavam incômodos nervosos, despedi-me do outro cavalheiro, dei o braço ao amigo enfermo, fi-lo tomar um cordial na mais próxima farmácia e só o deixei no bonde das Laranjeiras, quando o vi de todo restabelecido, a proibir-me que o acompanhasse até casa." — Carlos de Laet</p>
<p>Apesar dessas teses, críticos como Jean Michel Massa e Valentim Facioli afirmam que as enfermidades de Machado não passam de "mitos românticos". Para esse grupo, os biógrafos tendem a exagerar seus sofrimentos, o que seria fruto do "psicologismo que invadiu a crítica literária dos anos 30 e dos anos 40". Argumentam que na época muitos negros eram guindados ao Ministério e que o próprio Machado foi subindo socialmente, o que desvalidaria a tese de sentimento de inferioridade. </p>
<p>Contudo, outros críticos conectam a saúde de Machado com sua obra. O conto "Verba Testamentária" de Papéis Avulsos descreve uma crise epiléptica ([...] tinha ocasiões de cambalear; outras de escorrer-lhe pelo canto da boca um fio quase imperceptível de espuma.), enquanto que em Quincas Borba um dos personagens percebe que andava à toa, vertiginoso (Deu por si na Praça da Constituição.) </p>
<p>Memórias Póstumas de Brás Cubas conta em uma de suas linhas um problema nervoso em que o narrador vai andando conforme a perna lhe leva ([...] nenhum merecimento da ação me cabe, e sim às pernas que a fizeram), enquanto que no poema Suave Mari Magno há explicitamente o uso da palavra "convulsão": Arfava, espumava e ria,/ De um riso espúrio e bufão,/ Ventre e pernas sacudia,/ Na convulsão. Alguns notam que o Bentinho de Dom Casmurro, por ter se tornado uma pessoa fechada, taciturna, mal-humorada, podia sofrer de distimia, enquanto que seu companheiro Escobar sofria de transtorno obsessivo-compulsivo e de tiques motores, com possível controle sobre eles. Em 1991, O Alienista foi visto como a primeira contribuição brasileira à anti-psiquiatria e a escrita de Machado, que faz inúmeras referências à problemas mentais de saúde, vista como uma extensão de seu "sentimento de inferioridade por ser mulato, de origem pobre, órfão, e epiléptico".</p>
<p>Acredita-se que Machado de Assis tenha consultado um homem da região, Dr. Miguel Couto, e este lhe indicou brometo. Parece que a droga ingerida foi ineficaz e que, causando efeitos indesejáveis, obrigou Machado a seguir o conselho de um dos amigos para descontinuar o tratamento e optar pela homeopatia. Em seus últimos dias, morreu com uma úlcera cancerosa na boca, provavelmente derivada de seus diversos tiques nervosos, e que lhe impedia de ingerir qualquer alimento sólido.</p>


            
            



		    
     </div> <div>    <br /> <br />  <br />   <p class='text-center'> * * * </p>  <br /> <hr />  <br />  <br />      <br />         </div>                      
     

      </div>                   
</asp:Content>