<%@ Page Title="Raul Pompeia - O Ateneu - 03 / 12" Language="C#" MasterPageFile="~/PT/SitePTLivro.master" AutoEventWireup="true" CodeBehind="BR-06-03.aspx.cs" Inherits="Sanderlei.PT.AudioLivro.BR_06_03" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content=" Se em pequeno, movido por um vislumbre de luminosa prudência, enquanto aplicavam-se os outros à peteca, eu me houvesse entregado ao manso labor de fabricar documentos autobiográficos, para a oportuna confecção de mais uma infância célebre, certo não registraria, entre os meus episódios de predestinado, o caso banal da natação, de conseqüências, entretanto, para mim, e origem de dissabores como jamais encontrei tão amargos.  " /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>            
            <h1> Raul Pompeia - O Ateneu - 03 / 12	</h1>
            <br />
              <div class="embed-responsive embed-responsive-16by9">
               <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Uvxw1LqClZ4" frameborder="0" allowfullscreen></iframe>
              </div>  <br /><br /><br />   <br /><br /><br />                  
     </div>
          <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
         <br /> 
                <h2 class='text-center'>O Ateneu, de Raul Pompéia</h2>
                 <br /> 
                <h3 class='text-center'> III </h3>
                <br /> 


<p>Se em pequeno, movido por um vislumbre de luminosa prudência, enquanto aplicavam-se os outros à peteca, eu me houvesse entregado ao manso labor de fabricar documentos autobiográficos, para a oportuna confecção de mais uma infância célebre, certo não registraria, entre os meus episódios de predestinado, o caso banal da natação, de conseqüências, entretanto, para mim, e origem de dissabores como jamais encontrei tão amargos. </p>

<p>Natação chamava-se o banheiro, construído num terreno das dependências do Ateneu, vasta toalha d’água ao rés da terra, trinta metros sobre cinco, com escoamento para o Rio Comprido, e alimentada por grandes torneiras de chave livre. O fundo, invisível, de ladrilho, oferecia uma inclinação, baixando gradualmente de um extremo para outro. Acusava-se ainda mais esta diferença de profundidade por dois degraus convenientemente dispostos para que tomassem pé as crianças como os rapazes desenvolvidos. Em certo ponto a água cobria um homem. </p>

<p>Por ocasião dos intensos calores de fevereiro e marco e do fim do ano, havia ai dois banhos por dia. E cada banho era uma festa, naquela água gorda, salobra da transpiração lavada das turmas precedentes, que as dimensões do tanque impediam a devida renovação; turbulento debate de corpos nus, estreitamente cingidos no calção de malha rajado a cores, enleando-se os rapazes como lampreias, uns imergindo, reaparecendo outros, olhos injetados, cabelos a escorrer pela cara, vergões na pele de involuntárias unhadas dos companheiros, entre gritos de alegria, gritos de susto, gritos de terror; os menores agrupados no raso, dando-se as mãos em cacho, espavoridos, se algum mais forte chegava. </p>

<p>Dos maiores, alguns havia que faziam medo realmente, singrando a braçadas, levando a ombro a resistência d’água; outros se precipitavam cabeça para baixo, volteando os pés no ar como cauda de peixe, prancheando sem ver a quem. E, borbulhando entre os nadadores, fartas ondas de ressaca se embarcavam e iam transbordar pelas imediações do banheiro alagando tudo. </p>

<p>Ao longo do tanque, corria o muro divisório, além do qual ficava a chácara particular do diretor. A distancia, viam-se as janelas de uma parte da casa, onde às vezes eram recolhidos os estudantes enfermos, fechadas sempre a venezianas verdes. </p>

<p>Trepada ao muro e meio escondida por uma moita de bambus e ramos de hera, vinha Ângela, a canarina, ver os banhos da tarde. Lançava pedrinhas aos rapazes; os rapazes mandavam-lhe beijos e mergulhavam, buscando o seixo. Ângela, torcendo os pulsos, reclinando-se para trás, ria perdidamente um grande riso, desabrochado em carola de flor através dos dentes alvos. </p>

<p>Ao primeiro banho, amedrontou-me a desordem movimentada. </p>

<p>Procurei o recanto dos menores. Determinava a disciplina a divisão dos banhistas em três turmas, conforme as classes de idade. Mas, o descuido da fiscalização permitia que as turmas se confundissem e o inspetor de serviço, com a varinha destinada aos retardatários, vigiava, afastado, de sorte que ficavam expostos os mais fracos aos abusos dos marmanjos que as espadanas d’água acobertavam. Mal tinha eu entrado, senti que duas mãos, no fundo, prendiam-me o tornozelo, o joelho. A um impulso violento cai de costas; a água abafou-me os gritos, cobriu-me a vista. Senti-me arrastado. Num desespero de asfixia, pensei morrer. Sem saber nadar, vi-me abandonado em ponto perigoso; e bracejava, à toa, imerso a desfalecer, quando alguém me amparou. Um grande tomou-me ao ombro e me depôs à borda, estendido, vomitando água. Levei algum tempo para me inteirar do que ocorrera. Esfreguei por fim os olhos e verifiquei que o Sanches me tinha salvo. “Ia afogar-se!” disse ele, amparando-me a cabeça enquanto me desempastava os cabelos de cima dos olhos. Meio aturdido ainda, contei-lhe efusivamente o que me haviam feito. “Perversos!” observou-me o colega com pena, e atribuiu a brutalidade a qualquer peste que fugira no atropelo dos nadadores, desvelando-se em solicitudes por tranqüilizar-me. Tive depois motivo, para crer que o perverso e a peste fora-o ele próprio, na intenção de fazer valer um bom serviço. </p>

<p>Mas a conseqüência imediata do fato foi que forcei a repugnância que o Sanches me causava e me fiz todo gratidão para com ele e intima amizade. Curiosa e acidentada tinha de ser essa minha aventura de apego e confiança. </p>

<p>No Ateneu formávamos a dois para tudo. Para os exercícios ginásticos, para a entrada na capela, no refeitório, nas aulas, para a saudação ao anjo da guarda, ao meio-dia, para a distribuição do pão seco depois do canto. Por amor da regularidade da organização militar, repartiam-se as três centenas de alunos em grupos de trinta, sob o direto comando de um decurião ou vigilante. Os vigilantes eram escolhidos por seleção de aristocracia, asseverava Aristarco. Vigilante era o Malheiro, o herói do trapézio; vigilante era o Ribas, a melhor vocalização do Orfeão; vigilante era o Mata, mirrado, corcundinha, de espinha quebrada, apelidado o mascate, melífluo no trato, nunca punido ninguém sabia por quê, reputação de excelente porque ninguém se lembrava de verificar, que, entretanto, Rebelo apontava como chefe da policia secreta do diretor; vigilante o Saulo, que tinha três distinções na instrução pública; vigilante Rômulo, mestre cook, por alcunha, uma besta, grandalhão, último na ginástica pela corpulência bamba, último nas aulas, dispensado do Orfeão pela garganta rachada de requinta velha, mas exercendo no colégio, por exceção de saliência na largura chata da sua incapacidade, as complexas e delicadas funções de zabumba da banda. Não sei se este jeito particular para o bombo, fórmula musical do anúncio, não sei se uma célebre herança que Rômulo esperava de afortunados parentes, verdade é que entre todos fora Rômulo apurado por Aristarco para o invejável privilégio de seu futuro genro. </p>

<p>Diversos outros vigilantes contavam-se como estes, eleitos por um critério que dava ensejo a que o escolhido por valentia à barra fixa representava no estudo um papel contristador; vice-versa, outro, como Ribas, exemplar nas aulas, magricela e esgotado, mal podia ao trapézio vacilar a acrobacia simplificada do prumo. </p>

<p>Sanches era também vigilante. </p>

<p>Estes oficiais inferiores da milícia da casa faziam-se tiranetes por delegação da suprema ditadura. Armados de sabres de pau com guardas de couro, tomavam a sério a investidura do mando e eram em geral de uma ferocidade adorável. Os sabres puniam sumariamente as infrações da disciplina na forma: duas palavras ao cerra-fila, perna frouxa, desvio notável do alinhamento. Regime siberiano, como se vê, do que resultava que os vigilantes eram altamente conceituados. </p>

<p>No caso particular da nossa fortuita aproximação, não podia deixar de influir consideravelmente a bela importância colegial do vigilante Sanches. Mas outras circunstâncias concertaram-se para determinar a nova feição das minhas disposições conforme se acentuou depois do incidente do banho. </p>

<p>Já me era lícito julgar iniciado na convivência intima da escola. Chamado por Mânlio a provas, consegui agradar, conquistando uma aura que me devia por algum tempo favorecer. Encontrei o Barbalho. Tinha a face marcada pelas minhas unhas; evitou-me. No recreio cometi a injustiça de ir deixando o Rebelo. Também o amável camarada tinha na boca um mau cheiro que lhe prejudicava a pureza dos conselhos; demais, falava prendendo a gente com dedos de torquês e soltando os aforismos a queima-roupa. Por seu lado o venerando colega correspondeu ao movimento massando-se comigo, e amuando. Durante as aulas, em que nos sentávamos perto um do outro, absorvia-se em sua desesperada atenção e era como se estivesse a muitas milhas. Se, todavia, por imprescindível necessidade tinha de me falar, então, dirigia-me a palavra com a habitual afabilidade de jovem cura. </p>

<p>Estava aclimado, mas eu me aclimara pelo desalento, como um encarcerado no seu cárcere. </p>

<p>Depois que sacudi fora a tranca dos ideais ingênuos, sentia-me vazio de animo; nunca percebi tanto a espiritualidade imponderável da alma: o vácuo habitava-me dentro. Premia-me a força das coisas; senti-me acovardado. Perdeu-se a lição viril de Rebelo: prescindir de protetores. Eu desejei um protetor, alguém que me valesse, naquele meio hostil e desconhecido, e um valimento direto mais forte do que palavras. </p>

<p>Se não houvesse olvidado as práticas, como a assistência pessoal do Rebelo, eu notaria talvez que pouco a pouco me ia invadindo, como ele observara, a efeminação mórbida das escolas. Mas a teoria é frágil e adormece como as larvas friorentas, quando a estação obriga. A letargia mora! pesava-me no declive. E, como se a alma das crianças, à maneira do físico, esperasse realmente pelos dias para caracterizar em definitivo a conformação sexual do indivíduo, sentia-me possuído de certa necessidade preguiçosa de amparo, volúpia de fraqueza em rigor imprópria do caráter masculino. Convencido de que a campanha do estudo e da energia moral não era precisamente uma cavalgada cotidiana, animada pelo clarim da retórica, como nas festas, e pelo verso enfático dos hinos, entristeceu-me a realidade crua. Desiludi-me dos bastidores da gloriosa parada, vendo-a pelo avesso. Nem todos os dias do militarismo enfeitam-se com a animação dos assaltos e das voltas triunfais; desmoralizava-me o ranram estagnado da paz das casernas, o prosaísmo elementar da faxina. </p>

<p>Com esta crise do sentimento casava-se o receio que me infundia o microcosmo do Ateneu. Tudo ameaça os indefesos. O desembaraço tumultuoso dos companheiros a recreação, a maneira fácil de conduzir o trabalho, pareciam-me traços de esmagadora superioridade; espantava-me a viveza dos pequenos, tão pequenos alguns! O braço do Sanches vinha assim salvar-me, segunda vez, de submersão, acudindo na vertigem do momento. </p>

<p>Eu não estudava; a minha conta era, entretanto, regular, por um concurso de elementos eventuais; direitos da recente matricula à benevolência, a minha recomendação ao Professor Mânlio, com os retalhos alinhavados de ciência anterior. Mantinha-me em satisfatória média; mas o risco da decadência era constante. O método constituía o pior obstáculo; sem o auxilio de alguém, mais prático, estava perdido. Sanches havia sem dúvida de valer-me com a sua capacidade de grande estudante, sobretudo com a boa vontade insinuativa que desinteressadamente manifestava. Sem falar no proveito que rendia esta afeição, empunhando por meu favor o terrível sabre de vigilante, com guardas de couro! </p>

<p>Com efeito não tardou que ele me desse a mão como a Minerva benigna de Fénelon. </p>

<p>Entrei pela geografia como em casa minha. As anfractuosidades marginais dos continentes desfaziam-se nas cartas, por maior brevidade do meu trabalho; os rios dispensavam detalhes complicados dos meandros e afluíam-me para a memória, abandonando o pendor natural das vertentes; as cordilheiras, imensa tropa de amestrados elefantes, arranjavam-se em sistemas de orografia facílima; reduzia-se o número das cidades principais do mundo, sumindo-se no chão, para que eu não tivesse de decorar tanto nome; arredondava-se a cota das populações, perdendo as frações importunas, com prejuízo dos recenseamentos e maior gravame dos úteros nacionais; uma mnemônica feliz ensinava-me a enumeração dos estados e das províncias. Graças à destreza do Sanches, não havia incidente estudado da superfície terrestre que se me não colasse ao cérebro como se fosse minha cabeça, por dentro, o que é por fora a esfera do mundo. </p>

<p>A seu turno a gramática abria-se como um cofre de confeitos pela Páscoa. Cetim cor de céu e açúcar. Eu escolhia a bel-prazer os adjetivos, como amêndoas adocicadas pelas circunstâncias adverbiais da mais agradável variedade; os amáveis substantivos! voavam-me à roda, próprios e apelativos, como criaturinhas de alfenim alado; a etimologia, a sintaxe, a prosódia, a ortografia, quatro graus de doçura da mesma gustação. Quando muito, as exceções e os verbos irregulares desgostavam-me a principio; como esses feios confeitos crespos de chocolate: levados a boca saborosíssimos. </p>

<p>A história pátria deliciou-me em quanto pôde. Desde os missionários da catequese colonizadora, que vinham ao meu encontro, com Anchieta, visões de bondade, recitando escolhidas estrofes do evangelho das selvas, mandando adiante, coroados de flores, pela estrada larga de areia branca, os columins alegres, aprendizes da fé e da civilização, acompanhados da turba selvagem do gentio cor de casca de árvores, emplumados, sarapintados de mil tintas, em respeitosa contrição de fetichismo domado, avultando do seio, do fundo da mata escura, como uma marcha fantástica de troncos. Até às eras da independência, evocação complicada de sarrafos comemorativos das alvoradas do Rocio e de anseios de patriotismo infantil; um príncipe fundido, cavalgando uma data, mostrando no lenço aos povos a legenda oficial do Ipiranga; mais abaixo, pontuadas pelas salvas do Santo Antônio, as aclamações de um povo mesclado que deixou morrer Tiradentes para se esbofar em vivas ao ramo de café da Domitila. </p>

<p>Cada página era um encanto, prefaciadas pela explicação complacente do colega. Graças à habilidade das suas apresentações, apertei a mão aos mais truculentos figurões do passado, aos mais poderosos. Antônio Salema, o cruel, sorriu-me; o Vidigal foi gentil; D. João VI deixou-me rapé nos dedos. Conheci de vista Mem de Sá, Maurício de Nassau, vi passar o herói mineiro, calmo, mãos atadas como Cristo, barba abundante de apóstolo das gentes, um toque de sol na fronte lisa e vasta, escavada pelo destino para receber melhor a coroa do martírio. </p>

<p>A história santa revelou-me este épico, quem o diria? — o cônego Roquette! E eu bebi a embriaguez musical dos capítulos como o canto profundo das catedrais. Ouvi suspirar a Crença, o idílio do Éden, o amor primitivo do Gênesis, invejado dos anjos, sob o olhar magnânimo dos leões; ouvi a queixa terna do primeiro par banido para a dor, para o trabalho; Adão vergonhoso, vestindo as parras da primeira pruderie, Eva a envolver a nudez jovem de lírios na túnica de ouro das madeixas, cobrindo com as mãos o ventre, obscenidade das mães, estigmatizada pela maldição de Deus. </p>

<p>E crescia o canto na abóbada e o órgão falava à tradição inteira do sofrimento humano suplantado pela divindade. Modulava-se a harmonia em suave gorjeio, entoando a elevação dos salmos, o êxtase sensual do Cântico dos Cânticos na boca da Sulamita, e a sedução de Booz enredado no estratagema honesto da ternura, e a melancolia trágica de Judite, e a serena glória de Ester, a princesa querida. </p>

<p>Subitamente, entreabria-se o quadro sonoro para irromper o coro das lamentações. Acabavam no ar, lucíolas extintas, os derradeiros sons da harpa de Davi; perdia-se em ecos a derradeira antístrofe Salomão; sumiu-se à extremidade do campo a imagem de Rute, ao braço o feixe louro de trigo; entrou a Hebréia sombria na tenda de Holofernes, levando nos lábios o beijo assassino; cobriu-se a aparição luminosa de Ester com o sono da noite de Mardoqueu. Era a gama dolente dos terrores. Clamavam as imprecações do dilúvio, os desesperos de Gomorra; flamejava no firmamento a espada do anjo de Senaqueribe; dialogavam em concerto tétrico as súplicas do Egito, os gemidos de Babilônia, as pedras condenadas de Jerusalém. Vozeava o tenebroso grave das pregações dos profetas. Embalde o fulgor das transfigurações, como o lívido fuzil, escancarava abertas de luz sobre a tormenta noturna; Ezequiel tinha a visão do Eterno; Elias visitava o Mistério numa escapada de chamas. Nada. A música solene era o miserere. Nem o clarão da alvorada de Belém na Judéia debelava a sombra, nem a miragem viva do Tabor. A epopéia agonizava ao rodar do século, ecoava numa caverna onde havia um túmulo; bradava triunfo um momento pela Ressurreição do Justo; morria, enfim, lento, lento com a prece dos mártires do anfiteatro, com a longínqua prece subterrânea dos refugiados das Catacumbas. </p>

<p>A doutrina cristã, anotada pela proficiência do explicador, foi ocasião de dobrado ensino que muito me interessou. Era o céu aberto, rodeado de altares, para todas as criações consagradas da fé. Curioso encarar a grandeza do Altíssimo; mas havia janelas para o purgatório a que o Sanches se debruçava comigo, cuja vista muito mais seduzia. E o preceptor tinha um tempero de unção na voz e no modo, uma sobranceria de diretor espiritual, que fala do pecado sem macular a boca. Expunha quase compungido, fincando o olhar no teto, fazendo estalar os dedos, num enlevo de abstração religiosa; expunha, demorando os incidentes, as mais cabeludas manifestações de Satanás no mundo. Nem ao menos dourava os chifres, que me não fizessem medo; pelo contrário, havia como que o capricho de surpreender com as fantasias do Mal e da Tentação, e, segundo o lineamento do Sanches, a cauda do demônio tinha talvez dois metros mais que na realidade. Insinuou-me, é certo, uma vez, que não é tão feio o dito, como o pintam. </p>

<p>O catecismo começou a infundir-me o temor apavorado dos oráculos obscuros. Eu não acreditava inteiramente. Bem pensando, achava que metade daquilo era invenção malvada do Sanches. E quando ele punha-se a contar histórias de castidade, sem atenção à parvidade da matéria do preceito teológico, mulher do próximo, Conceição da Virgem, terceiro-luxúria, brados ao céu pela sensualidade contra a natureza, vantagens morais do matrimônio, e porque a carne, a inocente carne, que eu só conhecia condenada pela quaresma e pelos monopolistas do bacalhau, a pobre carne do beef, era inimigo da alma; quando retificava o meu engano, que era outra a carne e guisada de modo especial e muito especialmente trinchada, eu mordia um pedacinho de indignação contra as calúnias à santa cartilha do meu devoto credo. Mas a coisa interessava e eu ia colhendo as informações para julgar por mim oportunamente. </p>

<p>Na tabuada e no desenho linear, eu prescindia do colega mais velho; no desenho, porque achava graça em percorrer os caprichosos traços, divertindo-me a geometria miúda como um brinquedo; na tatuada e no sistema métrico, porque perdera as esperanças de passar de medíocre como ginasta de cálculos, e resolvera deixar a Maurílio ou a quem quer que fosse o primado das cifras. </p>

<p>Em dois meses tínhamos vencido por alto a matéria toda do curso; e, com este preparo, sorria-me o agouro de magnífico futuro, quando veio a fatalidade desandar a roda. </p>

<p>Referi que Sanches me provocava uma repugnância de gosma. Depois do caso da natação, o reconhecimento predominou sobre a repulsa e eu admiti as assiduidades com que de então por diante me quis beneficiar o companheiro. Afinal, porém, tornou-me a aparecer o afastamento instintivo que me separava do rapaz. </p>

<p>Descrente da fraternidade do colégio, cuja personificação representava-me o Barbalho, eu temia o alvoroço do recreio. Conservar-me na sala das lições era uma medida de prudência. Estes intervalos regulamentares de descanso, aproveitava-os para me adiantar no curso. Pois bem, durante estes momentos de aplicação excepcional em que ficávamos a sós, eu e o grande, definiu-se o fundamento da antipatia pressentida. A franqueza da convivência aumentou dia a dia, em progresso imperceptível. Tomávamos lugar no mesmo banco. Sanches foi-se aproximando. Encostava-se, depois, muito a mim. Fechava o livro dele e lia no meu, bafejando-me o rosto com uma respiração de cansaço. Para explicar alguma coisa, distanciava-se um pouco; tomava-me, então, os dedos e amassava-me até doer a mão, como se fosse argila, cravando-me olhares de raiva injustificada. Volvia nova” mente às expressões de afeto e a leitura prosseguia, passando-me ele o braço ao pescoço como um furioso amigo. </p>

<p>Eu deixava tudo, fingindo-me insensível, com um plano de rompimento em idéia, embargado, todavia, pela falta de coragem. Não havia mal naquelas maneiras amigas; achava-as, simplesmente, despropositadas e importunas, máxime não correspondendo à mais insignificante manifestação da minha parte. </p>

<p>Notei que ele variava de atitude quando um inspetor mostrava a cabeça à entrada da sala e quando pretendia informar-me de alguma disciplina transcendente. </p>

<p>Então o mestre singular formalizava-se de gravidade severa e distante. Esta inconstância era o meu alarme. Foi afinal um entretenimento. Eu perdia muitas vezes o fio da leitura para atender às artimanhas daquela novíssima comédia. </p>

<p>Por um dia de muito calor, acabava ele de enunciar como um padre uma página de religião, os diversos atos de Contrição, de Atrição, de Fé, de Esperança, de Caridade, quando propôs que eu lhos repetisse sentado aos seus joelhos. Achei inútil a comodidade e repeti a lição passeando pela sala. Que diabo! Aquele sujeito queria tratar-me definitivamente como um bebê! Com pouco mais lhe daria o excesso de extremos para me oferecer uma volta de cueiros! Ah! que se ainda me vivesse no animo a bravura audaz que trouxera de casa, sem dúvida nenhuma há muito tempo que eu tinha despachado o Sanches com a cartilha pelas ventas. Mas eu era outro, e a vontade vegetava tenra e dúctil como um renovo, depois do aniquilamento da primeira decepção. Fui transferindo o conflito. </p>

<p>Às vezes a minha resistência passiva desapontava o preceptor. Ele encarava-me terrível, e como quem diz: “perde a proteção de um vigilante!”, ou disfarçava a impertinência em riso amarelo, numa abstrata expressão de fisionomia, que era aliás o facies de uma idéia fixa. </p>

<p>Os exercícios corporais efetuavam-se à tarde, uma hora depois do jantar, hora excelente, que habituava a digestão a segurar-se no estômago e não escorrer pela goela quando os estudantes se balançavam à barra fixa, pelas curvas. </p>

<p>Reconheci o belo campo das manobras quando lá fui pela primeira vez, depois da matricula; tive saudade das flâmulas sobre o gramal verde. Mesmo, porém, desmontada a alegria de encomenda das festas, era um sitio ameníssimo o campo. Descoberto a todo o céu, parecia mais abundante de ar; eu lá vingava os pulmões da compressão cerrada do regime interno. </p>

<p>Findos os exercícios, partia o Professor Bataillard, e, guardados por dois inspetores, o Silvino e o João Numa ou João Numa e o velho Margal, venerando inválido espanhol querido de todos, ou o Margal e o Conselheiro tínhamos, os alunos, um prazo de recreio até cair a noite. </p>

<p>Uma vez, ao escurecer, passeando eu calado, com o Sanches igualmente, vendo escapar o dia para além das montanhas, percebi que o meu companheiro balbuciava uma pergunta. Falou desatento, admirando o crepúsculo com a testa franzida, na meia abstração que era o seu ricto costumeiro. Estávamos a um rodeio da avenida que circundava o gramal, oposto à cancela onde conversavam os inspetores. Os colegas jogavam barra através da grama, ou se divertiam ao saut-de-mouton em pontos afastados. Como não apreendi a pergunta, o Sanches repetiu. Escapou-me involuntário o riso... Abarbava-me a mais rara espécie de pretendente! Eu ria com franqueza, mas abismado. Era de uma extravagância original aquele Sanches! Hoje, ele é engenheiro em uma estrada de ferro do sul, um grave engenheiro... </p>

<p>Vendo que não nos podíamos entender, meteu entre nós o esplendor da tarde, e resolvemos o embaraço concordando ambos num parecer unânime a respeito. </p>

<p>Durante os dias que se seguiram, Sanches esteve frio. Tive medo de perdê-lo. Deu-me as lições sem uma só das intragáveis ternuras. Exprimia-se brevemente, entre enfezado e triste. Suspeitei uma revolução de caráter e julguei ter achado o que me convinha: um amigo moderado, que me livrasse dos vexames da vida colegial dos pequenos. O caso era outro. Sanches compreendera que a ingenuidade tinha contraminado os zelos do seu ensino. Manobrava, então, para voltar à carga. Entretanto, deu-se o cuidado de insistir na preparação edificante. </p>

<p>Inventou uma análise dos Lusíadas, livro de exame, cuja dificuldade não cessava de encarecer. </p>

<p>Guiou-me ao canto nono, como a uma rua suspeita. Eu gozava criminosamente o sobressalto dos inesperados. Mentor levou-me por diante das estrofes, rasgando na face nobre do poema perspectivas de bordel a fumegar alfazema. Bárbaro! Havia um trajo de modéstia sobre a verdade do vocábulo; ele rasgava as túnicas de alto a baixo, grosseiramente. Fazia do meneio grácil de cada verso uma brutalidade ofensiva. Eu acompanhava-o sem remorso; reputava-me vagamente vitima, e me dava à crueldade, submisso, adormecido na vantagem da passividade. A análise aguilhoava as rimas; as rimas passavam, deixando a lembrança de um requebro impudente. E o ar severo do Sanches imperturbável. </p>

<p>Tomava cada período, cada oração, altamente, com o ademã sisudo do anatomista: sujeito, verbo, complementos, orações subordinadas; depois o significado, zás! um corte de escalpelo, e a frase rolava morta, repugnante, desentranhando-se em podridões infectas. </p>

<p>Iniciou da mesma forma um curso pitoresco de dicionário. O dicionário é o universo. Baba-se de esclarecimentos, mas atordoa, à primeira vista, como a agitação das grandes cidades desconhecidas. Encarreirados nas páginas consideráveis, os nomes seguem estranhamente com a numerosa prole dos derivados, ou sós, petits-maîtres faceiros, os galicismos; vaidosos dandies os de proveniência albiônica. Molestam-nos com a maneira desdenhosa, porque os não conhecemos. As dignificações prolongam-se intérminas, entrecruzam-se em confusa rede topográfica. O inexperiente não conquista um passo na imensa capital das palavras. Sanches estava afeito. Penetrou comigo até aos últimos albergues da metrópole, até à cloaca máxima dos termos chulos. Descarnou-me em caricatura de esqueleto a circunspeção magistral do Lexicon, como poluíra a elevação parnasiana do poema. </p>

<p>Eu me sentia amesquinhado sob o peso das revelações. Causava terror aquela sabedoria de coisas nunca sonhadas. O honrado diretor espiritual percebeu que havia agora um ascendente de domínio que me curvava. Olhava-me então de frente e tinha ousados risos de malícia. Depois dos dias de reserva, chegou-se de novo com uma segurança de possuidor forte. Eu andava num deplorável desmantelo de energia. Rebelo, de vez em quando, acabrunhava-me, através dos óculos azuis, com um olhar de desprezo ou condolência ainda mais aviltante. Meu pai vinha ver-me todas as semanas; eu mostrava os prêmios de aplicação, conversava de casa; </p>

<p>o resto calava. Sempre desconfiado e receoso dos outros, o meu companheiro era quase exclusivamente Sanches. Sempre juntos eu e ele. Sabia-se no Ateneu que ele era meu explicador, supunham até que pago. Não causavam estranheza as nossas relações. </p>

<p>Contudo Sanches, como os mal-intencionados, fugia dos lugares concorridos. Gostava de vaguear comigo, à noite, antes da ceia, cruzando cem vezes o pátio de pouca luz, cingindo-me nervosamente, estreitamente até levantar-me do chão. Eu aturava, imaginando em resignado silêncio o sexo artificial da fraqueza que definira Rebelo. </p>

<p>Estimulado pelo abandono, que lhe parecia assentimento tácito, Sanches precipitou um desenlace. Por uma tarde de aguaceiro errávamos pelo saguão das bacias, escuro, úmido, recendendo ao cheiro das toalhas mofadas e dos ingredientes dentifrícios, solidão favorável, multiplicada pelos obstáculos à vista que ofereciam enormes pilares quadrados em ordem a sustentar o edifício, — quando, sem transição, o companheiro chegou-me a boca ao rosto e falou baixinho. </p>

<p>Só a voz, o simples som covarde da voz, rastejante, colante, como se fosse cada sílaba uma lesma, horripilou-me, feito o contato de um suplício imundo. Fingi não ter ouvido; mas houve intimamente a explosão de todo o meu asco por semelhante indivíduo e muito calmo, desviando apenas a vista, pretextei a falta de um lenço, que me endefluxara a friagem e... fui buscá-lo. </p>

<p>Fora da zona magnética em que me cativava o bom amigo, concertaram-se os meus instintos sopitados de revolta e Sanches passou a ser um desconhecido. Sacrificava-se de golpe o amigo, o explicador e o vigilante: um rasgo de heroicidade. Ao primeiro encontro depois do rompimento, o homem viu que estava tudo acabado. Andou a rondar-me, temperando o olhar com um brilho de facadas. </p>

<p>A ocasião é que não era a melhor para o conflito. Conveniências do ensino tinham feito dividir-se em duas turmas a aula do Professor Mânlio, e eu fora incluído na seção confiada ao Sanches, como auxiliar idôneo. A conseqüência foi o que devia ser. Maltratado e condenado pelo ajudante, provando mal em razão do sobressalto no exame de verificação a que me sujeitou o professor, desmoralizado em repreensão solene com grande regozijo do Sanches, jurei vingança. Escandalizaria o mundo com uma vadiação sem exemplo! Percorrera a matéria toda em rápida antecipação de estudo. Isto, porém, não bastava. Bastasse! foi o meu lema. E toca a desandar. Fiquei abaixo do Barbalho, aliás fora de classificação decente; fiquei abaixo do Álvares. Fui o último da aula! Resultado razoável, para emprego de uma energiazinha que despontava. </p>

<p>Ao mesmo tempo, como os filósofos atribulados, busquei a doce consolação dos astros. </p>

<p>Aristarco iniciara um curso noturno de cosmografia. </p>

<p>Estrelas era com ele. O nobre ensino! Nenhum professor, sob pena de expulsão, abalançava-se a intrometer-se nas onze varas da camisola de astrólogo. E vissem-no, à janela, indicando as constelações, impelindo-as através da noite com o pontudo dedo! Nós discípulos, não víamos nada; mas admirávamos. Bastava ele delinear sabiamente um agrupamento estelino às alturas, para cada um de nós por seu lado ficar mais a quo. E voava, fugindo, a poeira fosforescente. </p>

<p>Quanto a mim, o que sobretudo me maravilhava era a coragem com que Aristarco fisgava os astros, quando todos sabem que apontar estrelas faz criar verrugas. </p>

<p>Uma vez, muito entusiasmado, o ilustre mestre mostrou-nos o Cruzeiro do Sul. Pouco depois, cochichando com o que sabíamos de pontos cardeais, descobrimos que a janela fazia frente para o norte; não atinamos. Aristarco reconheceu o descuido: não quis desdizer-se. Lá ficou a contragosto o Cruzeiro estampado no hemisfério da estrela polar. </p>

<p>Eu tomei amor às coisas do espaço e estudava profundamente a mecânica do infinito pelo compêndio de Abreu. </p>

<p>Para as noites brumosas, Aristarco tinha os aparelhos. Uma infinidade de maquinismos do ensino astronômico, exemplificando o sistema solar, a teoria dos eclipses, a gravitação dos satélites, as esferas concêntricas, terrestre e celeste; a de dentro, de cartão lustrado; a de fora, de vidro. Um atravancamento indescritível, sobre a mesa, de estrelas e arames torcidos, rodas dentadas de latão, lâmpadas frouxas de nafta parodiando o sol. Aristarco dava à manivela e girava tudo. Com o pince-nez grosso de tartaruga, à ponta do nariz, dominava o tropel dos mundos. </p>

<p>“Vêem, dizia, explicando a natureza, vêem a minha mão aqui?” 
Mostrava a mão direita, ao realejo, bela manopla felpuda de fazer inveja a Esaú: 
“É a mão da Providência!” 
</p>

                <br />  <br />  <br />  <br />  <br />  <br /> 
         </div>
      </div>     
</asp:Content>