<%@ Page Title="Raul Pompeia - O Ateneu - 02 / 12" Language="C#" MasterPageFile="~/PT/SitePTLivro.master" AutoEventWireup="true"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder11" runat="server">   
    <meta name="description" content=" De manhã, à hora regulamentar, compareci. O diretor, no escritório do estabelecimento, ocupava uma cadeira rotativa junto à mesa de trabalho. Sobre a mesa, um grande livro abria-se em colunas maciças de escrituração e linhas encarnadas.  " /> 
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder12" runat="server">
    <!-- Conteudo  --> 
      <div class='container panel-body'>
        <div class='col-xs-12 col-md-12 text-center'>            
            <h1> Raul Pompeia - O Ateneu - 02 / 12	</h1>
            <br />
              <div class="embed-responsive embed-responsive-16by9">
               <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/UY8MU3GytCI" frameborder="0" allowfullscreen></iframe>
              </div>  <br /><br /><br />   <br /><br /><br />                  
     </div> 
         <div class='col-xs-12 col-md-12 text-justify' style='line-height:1.7'>
         <br /> 
                <h2 class='text-center'>O Ateneu, de Raul Pompéia</h2>
                 <br /> 
                <h3 class='text-center'> II </h3>
                <br /> 

           
<p>Abriam-se as aulas a 15 de fevereiro. </p>

<p>De manhã, à hora regulamentar, compareci. O diretor, no escritório do estabelecimento, ocupava uma cadeira rotativa junto à mesa de trabalho. Sobre a mesa, um grande livro abria-se em colunas maciças de escrituração e linhas encarnadas. </p>

<p>Aristarco, que consagrava as manhãs ao governo financeiro do colégio, conferia, analisava os assentamentos do guarda-livros. De momento a momento entravam alunos. Alguns acompanhados. </p>

<p>A cada entrada, o diretor lentamente fechava o livro, marcando a página com um alfanje de marfim; fazia girar a cadeira e soltava interjeições de acolhimento, oferecendo episcopalmente a mão peluda ao beijo contrito e filial dos meninos. Os maiores, em regra, recusavam-se à cerimônia e partiam com um simples aperto de mão. </p>

<p>O rapaz desaparecia, levando o sorriso pálido na face, saudoso da vadiação ditosa das férias. O pai, o correspondente, o portador, despedia-se, depois de banais cumprimentos, ou palavras a respeito do estudante, amenizadas pela gracinha da bonomia superior de Aristarco, que punha habilmente um sujeito fora de portas com o riso fanhoso e o simples modo impelido de segurar-lhe os dedos. </p>

<p>A cadeira girava de novo à posição primitiva; o livro da escrituração espalmava outra vez as páginas enormes; e a figura paternal do educador desmanchava-se, volvendo a simplificar-se na esperteza atenta e seca do gerente. </p>

<p>A este vaivém de atitudes, feição dupla de uma mesma individualidade e contingência comum dos sacerdócios, estava tão habituado o nosso diretor, que nenhum esforço lhe custava a manobra. O especulador e o levita ficavam-lhe dentro em camaradagem intima, bras dessus, bras dessous. Sabiam, sem prejuízo da oportunidade, aparecer por alternativa ou simultaneamente; eram como duas almas inconhas num só corpo. </p>

<p>Soldavam-se nele o educador e o empresário uma perfeição rigorosa de acordo, dois lados da mesma medalha: opostos, mas justapostos. </p>

<p>Quando meu pai entrou comigo, havia no semblante de Aristarco uma pontinha de aborrecimento. Decepção talvez de estatística; o número dos estudantes novos não compensando o número dos perdidos, as novas entradas não contrabalançando as despesas do fim do ano. Mas a sombra de despeito apagou-se logo, como o resto de túnica que apenas tarda a sumir-se numa mutação à vista; e foi com uma explosão de contentamento que o diretor nos acolheu. </p>

<p>Sua diplomacia dividia-se por escaninhos numerados, segundo a categoria de recepção que queria dispensar. Ele tinha maneiras de todos os graus, segundo a condição social da pessoa. As simpatias verdadeiras eram raras. No âmago de cada sorriso, morava-lhe um segredo de frieza que se percebia bem. E duramente se marcavam distinções políticas, distinções financeiras, distinções baseadas na crônica escolar do discípulo, baseadas na razão discreta das notas do guarda-livros. Às vezes, uma criança sentia a alfinetada no jeito da mão a beijar. Sala indagando consigo o motivo daquilo, que não achava em suas contas escolares... O pai estava dois trimestres atrasado. </p>

<p>Por diversas causas a minha recepção devia ser das melhores. Efetivamente; Aristarco levantou-se ao nosso encontro e nos conduziu à sala especial das visitas. </p>

<p>Saiu depois a mostrar o estabelecimento, as coleções, em armários, dos objetos próprios para facilitar o ensino. Eu via tudo curiosamente, sem perder os olhares dos colegas desconhecidos, que me fitavam muito ancho na dignidade do uniforme em folha. O edifício fora caiado e pintado durante as férias, como os navios que aproveitam o descanso nos portos para uma reforma de apresentação. Das paredes pendiam as cartas geográficas, que eu me comprazia de ver como um itinerário de grandes viagens planejadas. Havia estampas coloridas em molduras negras, assuntos de história santa e desenho grosseiro, ou exemplares zoológicos e botânicos, que me revelavam direções de aplicação estudiosa em que eu contava triunfar. Outros quadros vidraçados exibiam sonoramente regras morais e conselhos muito meus conhecidos de amor à verdade, aos pais, e temor de Deus, que estranhei como um código de redundância. Entre os quadros, muitos relativos ao Mestre — os mais numerosos; e se esforçavam todos por arvorar o mestre em entidade incorpórea, argamassada de pura essência de amor e suspiros cortantes de sacrifício, ensinando-me a didascalolatria que eu, de mim para mim, devotamente, jurava desempenhar à risca. Visitamos o refeitório, adornado de trabalhos a lápis dos alunos, a cozinha de azulejo, o grande pátio interno dos recreios, os dormitórios, a capela... De volta à sala de recepção, adjacente à da entrada lateral e fronteira ao escritório, fui apresentado ao Professor Mânlio, aula superior de primeiras letras, um homem aprumado, de barba toda grisalha e cerrada, pessoa excelente, desconfiando por sistema de todos os meninos. </p>

<p>Durante o tempo da visita, não falou Aristarco senão das suas lutas, suores que lhe custava a mocidade e que não eram justamente apreciados. “Um trabalho insano! Moderar, animar, corrigir esta massa de caracteres, onde começa a ferver o fermento das inclinações; encontrar e encaminhar a natureza na época dos violentos ímpetos; amordaçar excessivos ardores; retemperar o animo dos que se dão por vencidos precocemente; espreitar, adivinhar os temperamentos; prevenir a corrupção; desiludir as aparências sedutoras do mal; aproveitar os alvoroços do sangue para os nobres ensinamentos; prevenir a depravação dos inocentes; espiar os sítios obscuros; fiscalizar as amizades; desconfiar das hipocrisias; ser amoroso, ser violento, ser firme; triunfar dos sentimentos de compaixão para ser correto; proceder com segurança, para depois duvidar; punir para pedir perdão depois... Um labor ingrato, titânico, que extenua a alma, que nos deixa acabrunhados ao anoitecer de hoje, para recomeçar com o dia de amanhã... Ah! meus amigos, conclui ofegante, não é o espírito que me custa, não é o estudo dos rapazes a minha preocupação... É o caráter! Não é a preguiça o inimigo, é a imoralidade!” Aristarco tinha para esta palavra uma entonação especial, comprimida e terrível, que nunca mais esquece quem a ouviu dos seus lábios. “A imoralidade!” </p>

<p>E recuava tragicamente, crispando as mãos. “Ah! mas eu sou tremendo quando esta desgraca nos escandaliza. Não! Estejam tranqüilos os pais! No Ateneu, a imoralidade não existe! Velo pela candura das crianças, como se fossem, não digo meus filhos: minhas próprias filhas! O Ateneu é um colégio moralizado! E eu aviso muito a tempo... Eu tenho um código...” Neste ponto o diretor levantou-se de salto e mostrou um grande quadro à parede. “Aqui está o nosso código. Leiam! Todas as culpas são prevenidas, uma pena para cada hipótese: o caso da imoralidade não está lá. O parricídio não figurava na lei grega. Aqui não está a imoralidade. Se a desgraça ocorre, a justiça é o meu terror e a lei é o meu arbítrio! Briguem depois os senhores pais!...” </p>

<p>Afianço-lhes que o meu tremeu por mim. Eu, encolhido, fazia em superlativo a metáfora sabida das varas verdes. Notando a minha perturbação, o diretor desvaneceu-se em afagos. “Mas para os rapazes dignos eu sou um pai!... os maus eu conheço: não são as crianças, principalmente como você, o prazer da família, e que há de ser, estou certo, uma das glórias do Ateneu. Deixem estar...” Eu tomei a sério a profecia e fiquei mais calmo. </p>

<p>Quando meu pai saiu, vieram-me lágrimas, que eu tolhi a tempo de ser forte. Subi ao salão azul, dormitório dos médios, onde estava a minha cama; mudei de roupa, levei a farda ao número 54 do depósito geral, meu número. Não tive coragem de afrontar o recreio. Via de longe os colegas, poucos àquela hora, passeando em grupos, conversando amigavelmente, sem animação, impressionados ainda pelas recordações de casa; hesitava em ir ter com eles, embaraçado da estréia das calças longas, como um exagero cômico, e da sensação de nudez à nuca, que o corte recente dos cabelos desabrigara em escândalo. João Numa, inspetor ou bedel, baixote, barrigudo, de óculos escuros, movendo-se com vivacidade de bácoro alegre, veio achar-me indeciso, à escada do pátio. “Não desce, a brincar?” perguntou bondosamente. “Vamos, desça, vá com os outros.” O amável bácoro tomou-me pela mão e descemos juntos. </p>

<p>O inspetor deixou-me entre dois rapazinhos, que me trataram com simpatia. </p>

<p>Às onze horas, a sineta deu o sinal das aulas. Os meus bons companheiros, de classes atrasadas, indicaram a sala de ensino superior de primeiras letras, que devia ser a minha, e se despediram. </p>

<p>O Professor Mânlio, a quem eu fora recomendado, recomendou-me por sua vez ao mais sério dos seus discípulos, o honrado Rebelo. Rebelo era o mais velho e tinha óculos escuros como João Numa. O vidro curvo dos óculos cobria-lhe os olhos vigorosamente, monopolizando a atenção no interesse único da mesa do professor. Como se fosse pouco, o zeloso estudante fazia concha com as mãos às têmporas, para impedir o contrabando evasivo de algum olhar escapado ao monopólio do vidro. </p>

<p>Este luxo de aplicação não provinha do simples empenho de fazer atitude de exemplar. Rebelo sofria da vista, tanto que muito tarde pudera entregar-se aos estudos. Recebeu-me com um sorriso benévolo de avô; afastou-se um pouco para me dar lagar e esqueceu-me incontinenti, para afundar-se na devoradora atenção que era o seu apanágio. </p>

<p>Os companheiros de classe eram cerca de vinte; uma variedade de tipos que me divertia. O Gualtério, miúdo, redondo de costas, cabelos revoltos, motilidade brusca e caretas de símio — palhaço dos outros, como dizia o professor; o Nascimento, o bicanca, alongado por um modelo geral de pelicano, nariz esbelto, curvo e largo como uma foice; o Álvares, moreno, cenho carregado, cabeleira espessa e intonsa de vate de taverna, violento e estúpido, que Mânlio atormentava, designando-o para o mister das plataformas de bonde, com a chapa numerada dos recebedores, mais leve de carregar que a responsabilidade dos estudos; o Almeidinha, claro, translúcido, rosto de menina, faces de um rosa doentio, que se levantava para ir à pedra com um vagar lânguido de convalescente; o Maurílio, nervoso, insofrido, fortíssimo em tabuada: cinco vezes três, vezes dois, noves fora, vezes sete?... Ia estava Maurílio, trêmulo, sacudindo no ar o dedinho esperto... olhos fúlgidos rosto moreno, marcado por uma pinta na testa; o Negrão, de ventas acesas, lábios inquietos, fisionomia agreste de cabra, canhoto e anguloso, incapaz de ficar sentado três minutos, sempre à mesa do professor e sempre enxotado, debulhando um risinho de pouca-vergonha, fazendo agrados ao mestre, chamando-lhe bonzinho, aventurando a todo ensejo uma tentativa de abraço que Mânlio repelia, precavido de confianças; Batista Carlos, raça de bugre, válido, de má cara, coçando-se muito, como se o incomodasse a roupa no corpo, alheio às coisas da aula, como se não tivesse nada com aquilo, espreitando apenas o professor para aproveitar as distrações e ferir a orelha aos vizinhos com uma seta de papel dobrado. Às vezes a seta do bugre ricochetava até à mesa de Mânlio. Sensação; suspendiam-se os trabalhos; rigoroso inquérito. Em vão, que os partistas temiam-no e ele era matreiro e sonso para disfarçar. </p>

<p>Dignos de nota havia ainda o Cruz, tímido, enfiado, sempre de orelha em pé, olhar covarde de quem foi criado a pancadas, aferrado aos livros, forte em doutrina cristã, fácil como um despertador para desfechar as lições de cor, perro como uma cravelha para ceder uma idéia por conta própria; o Sanches, finalmente, grande, um pouco mais moço que o venerando Rebelo, primeiro da classe, muito inteligente, vencido apenas por Maurílio, na especialidade dos noves fora vezes tanto, cuidadoso dos exercícios, êmulo do Cruz na doutrina, sem competidor na análise, no desenho linear, na cosmografia. </p>

<p>O resto, uma cambadinha indistinta, adormentados nos últimos bancos, confundidos na sombra preguiçosa do fundo da sala. </p>

<p>Fui também recomendado ao Sanches. Achei-o supinamente antipático: cara extensa, olhos rasos, mortos, de um pardo transparente, lábios úmidos, porejando baba, meiguice viscosa de crápula antigo. Era o primeiro da aula. Primeiro que fosse do coro dos anjos, no meu conceito era a derradeira das criaturas. </p>

<p>Entretinha-me a espiar os companheiros, quando o professor pronunciou o meu nome. Fiquei tão pálido que Mânlio sorriu e perguntou-me, brando, se queria ir à pedra. Precisava examinar-me. </p>

<p>De pé, vexadíssimo, senti brumar-se-me a vista, numa fumaça de vertigem. Adivinhei sobre mim o olhar visguento do Sanches, o olhar odioso e timorato do Cruz, os óculos azuis do Rebelo, o nariz do Nascimento, virando devagar como um leme; esperei a seta do Carlos, o quinau do Maurílio, ameaçador, fazendo cócegas ao teto, com o dedo feroz; respirei no ambiente adverso da maldita hora, perfumado pela emanação acre das resinas do arvoredo próximo, uma conspiração contra mim da aula inteira, desde as bajulações de Negrão até à maldade violenta do Álvares. Cambaleei até à pedra. O professor interrogou-me; não sei se respondi. Apossou-se-me do espírito um pavor estranho. Acovardou-me o terror supremo das exibições, imaginando em roda a ironia má de todos aqueles rostos desconhecidos. Amparei-me à tábua negra, para não cair; fugia-me o solo aos pés, com a noção do momento; envolveu-me a escuridão dos desmaios, vergonha eterna! liquidando-se a última energia... pela melhor das maneiras piores de liquidar-se uma energia. </p>

<p>Do que se passou depois, não tenho idéia. A perturbação levou-me a consciência das coisas. Lembro-me que me achei com o Rebelo, na rouparia, e o Rebelo animava-me com um esforço de bondade sincero e comovedor. </p>

<p>Rebelo retirou-se e eu, em camisa, acabrunhado, amargando o meu desastre, enquanto o roupeiro procurava o gavetão 54, fiquei a considerar a diferença daquela situação para o ideal de cavalaria com que sonhara assombrar o Ateneu. </p>

<p>Como tardava o criado, apanhei aborrecido um folheto que ali estava à mesa dos assentos, entradas de enxoval, registros de lavanderia. Curioso folheto, versos e estampas... Fechei-o convulsamente com o arrependimento de uma curiosidade perversa. Estranho folheto! Abri-o de novo. Ardia-me à face inexplicável incêndio de pudor, constrangia-me a garganta esquisito aperto de náusea. Escravizava-me, porém, a sedução da novidade. Olhei para os lados com um gesto de culpado; não sei que instinto me acordava um sobressalto de remorso. Um simples papel, entretanto, borrado na tiragem rápida dos delitos de imprensa. Arrostei-o. O roupeiro veio interromper-me. “Larga daí! disse com brutalidade, isso não é para menino!” E retirou o livrinho. </p>

<p>Esta impressão viva de surpresa curou-me da lembrança do meu triste episódio, crescendo na imaginação como as visões, absorvendo-me as idéias. Zumbia-me aos ouvidos a palavra aterrada de Aristarco... Sim, devia ser isto: um entravamento obscuro de formas despidas, roupas abertas, um turbilhão de frades bêbados, deslocados ao capricho de todas as deformidades de um monstruoso desenho, tocando-se, saltando a sarabanda diabólica sem fim, no empastado negrume da tinta do prelo; aqui e ali, o raio branco de uma falha, fulminando o espetáculo e a gravura, como o estigma complementar do acaso. </p>

<p>A rouparia ocupava grande parte do subchão do imenso edifício, entre o vigamento do soalho e a terra cimentada. Outra parte era destinada aos lavatórios, centenas de bacias, ao longo das paredes e pouco acima num friso de madeira os copos e as escovas de dentes. Terceiro compartimento, além destes, acomodava o arsenal dos aparelhos ginásticos e o dormitório da criadagem. Da rouparia para o recreio central atravessava-se obliquamente o saguão das bacias. Logo a sair ao pátio encontrei o benévolo Rebelo, que me esperava. Insistiu com um requinte importuno de complacência sobre o meu incidente, desculpando-me, explicando-me, absolvendo-me; tornou-se insuportável. Para mudar de conversa, pedi informações acerca do nosso professor. Deu-mas ótimas, nem outras daria um aluno exemplar como ele. Nenhum mestre é mau para o bom discípulo, afirmava uma das máximas da parede. </p>

<p>Era hora de descanso; passeávamos, conversando. Falamos dos colegas. Vi então, de dentro da brandura patriarcal do Rebelo, descascar-se uma espécie de inesperado Tersito, produzindo injúrias e maldições. “Uma corja! Não imagina, meu caro Sérgio. Conte como uma desgraça ter de viver com esta gente.” E esbeiçou um lábio sarcástico para os rapazes que passavam. “Ai vão as carinhas sonsas, generosa mocidade... Uns perversos! Têm mais pecados na consciência que um confessor no ouvido; uma mentira em cada dente, um vicio em cada polegada de pele. Fiem-se neles. São servis, traidores, brutais, adulões. Vão juntos. Pensa-se que são amigos... Sócios de bandalheira! Fuja deles, fuja deles. Cheiram a corrupção, empestam de longe. Corja de hipócritas! Imorais! Cada dia de vida tem-lhes vergonha da véspera. Mas você é criança; não digo tudo o que vale a generosa mocidade. Com eles mesmos há de aprender o que são... Aquele é o Malheiro, um grande em ginástica. Entrou graúdo, trazendo para cá os bons costumes de quanto colégio por ai. O pai é oficial. Cresceu num quartel no meio da chacota das praças. Forte como um touro, todos o temem, muitos o cercam, os inspetores não podem com ele; o diretor respeita-o; faz-se a vista larga para os seus abusos... Este que passou por nós, olhando muito, é o Cândido, com aqueles modos de mulher, aquele arzinho de quem saiu da cama, com preguiça nos olhos... Este sujeito... Há de ser seu conhecido. Mas faço exceções: ali vem o Ribas, está vendo? feio, coitadinho! como tudo, mas uma pérola. É a mansidão em pessoa. Primeira voz do Orfeão, uma vozinha de moça que o diretor adora. É estudioso e protegido. Faz a vida cantando como os serafins. Uma pérola!” </p>


<p>
— 

Ali está um de joelhos... 
</p>

<p>
— 

De joelhos... Não há perguntar; é o Franco. Uma alma penada. Hoje é o primeiro dia, ali está de joelhos o Franco. Assim atravessa as semanas, os meses, assim o conheço, nesta casa, desde que entrei. De joelhos como um penitente expiando a culpa de uma raça. O diretor chama-lhe cão, diz que tem calos na cara. Se não tivesse calos no joelho, não haveria canto do Ateneu que ele não marcasse com o sangue de uma penitência. O pai é de Mato Grosso; mandou-o para aqui com uma carta em que o recomendava como incorrigível, pedindo severidade. O correspondente envia de tempos a tempos um caixeiro que faz os pagamentos e deixa lembranças. Não sai nunca... Afastemo-nos que aí vem um grupo de gaiatos. 
</p>


<p>Um tropel de rapazes atravessou-nos a frente, provocando-me com surriadas. </p>

<p>“Viu aquele da frente, que gritou calouro? Se eu dissesse o que se conta dele... aqueles olhinhos úmidos de Senhora das Dores... Olhe; um conselho; faça-se forte aqui, faça-se homem. Os fracos perdem-se. </p>

<p>“Isto é uma multidão; é preciso força de cotovelos para romper. Não sou criança, nem idiota; vivo só e vejo de longe; mas vejo. Não pode imaginar. Os gênios fazem aqui dois sexos, como se fosse uma escola mista. Os rapazes tímidos, ingênuos, sem sangue, são brandamente impelidos para o sexo da fraqueza; são dominados, festejados, pervertidos como meninas ao desamparo. Quando, em segredo dos pais, pensam que o colégio é a melhor das vidas, com o acolhimento dos mais velhos, entre brejeiro e afetuoso, estão perdidos... Faça-se homem, meu amigo! Comece por não admitir protetores.” </p>

<p>Ia por diante Rebelo com os extraordinários avisos, quando senti puxarem-me a blusa. Quase cai. Voltei-me; vi a distancia uma cara amarela, de gordura balofa, olhos vesgos sem pestanas, virada para mim, esgarçando a boca em careta de riso cínico. Um sujeito evidentemente mais forte do que eu. Não obstante apanhei com raiva um pedaço de telha e arremessei O tratante livrou-se, injuriando-me com uma gargalhada, e sumiu-se. “Muito bem”, aplaudiu Rebelo. E à pergunta que fiz, informou: aquele desagradável rapaz era o Barbalho, que havia de ser um dia preso como gatuno de jóias, nosso companheiro da aula primária, do número dos esquecidos nos bancos do fundo. </p>

<p>O Professor Mânlio teve a bondade de adiar o meu exame, e, para salvar-me das conseqüências do escárnio do desastrado incidente da primeira aula, obsequiou-me na seguinte com as melhores palavras de animação. Os rapazes foram generosos. Maurílio, acariciou-me a cabeça mimosamente, provando que sabia ser bom o dedinho implacável dos argumentos. Só o amarelo dos olhos vesgos teimava em fazer gaifonas à socapa. </p>

<p>Depois do jantar não tornei a ver o Rebelo. Como freqüentava algumas aulas extraordinárias do curso superior, recolhia-se a certas horas para as salas de cima. </p>

<p>A sala do Professor Mânlio era ao nível do pátio, em pavilhão independente do edifício principal, com duas outras do curso primário, o alojamento da banda de música e o salão suplementar de recreio, vantajoso em dias de chuva. Formando ângulo reto com esta casa, uma extensa construção de tijolo e tábuas pintadas, sala geral do estudo no pavimento térreo e dormitório em cima, concorria para fechar metade do quadrilátero do pátio, que o grande edifício completava, estendendo-se em duas alas, como os braços da reclusão severa. No fundo desta caixa desmedida de paredes, dilatava-se um areal claro, estéril, insípido como a alegria obrigatória, algumas árvores de cambucá mostravam, em roda, a folhagem fixa, com o verdor morto das palmas de igreja, alourada a esmo da senilidade precoce dos ramos que sofrem, como se não coubesse a vegetação no internato; a um canto, esgalgado cipreste subia até às goteiras, tentando fugir pelos telhados. </p>

<p>Sem o Rebelo, achei-me ai como perdido, em meio dos rapazes. Os conhecidos da aula desapareciam no tumulto que as salas todas despejavam. </p>

<p>Nem um só de quem me pudesse aproximar. Rente com a parede, para que me não dessem atenção, insinuei-me até o lugar donde o inspetor Silvino, um grande magro, de avultado nariz e suíças dilaceradas, olhar miado e vivo como chispas, em órbitas de antro, fiscalizava o recreio, graduando a folgança, à mercê de um temível canhenho. Sentava-se à entrada do portão do lavatório. Um pouco além da cadeira do Silvino, fiquei a salvo. Do seguro retiro avistava, no terreiro, fresco das largas sombras da hora, o movimento dos colegas. </p>

<p>Num ponto e noutro formavam-se pequenos sarilhos, condensando irregularmente a dispersão dos alunos. Eram os pobres novatos que os veteranos sovavam à cacholeta, fraternalmente. </p>

<p>Perto de mim vi o Franco. Sempre de penitência; em pé, cara contra a parede. Como Silvino dava-lhe as costas, divertia-se a pegar moscas para arrancar a cabeça e ver morrer o bichinho na palma da mão. Perguntei-lhe por que estava de castigo. Sem olhar, de mau modo: “Lá sei! disse ele. Porque me mandaram”. E continuou a pegar as moscas. Franco era um rapazola de quatorze anos, raquítico, de olhos pasmados, face lívida, pálpebras pisadas. À fronte, com a expressão vaga dos olhos e obliqüidade dolorida dos supercílios, pousava-lhe uma névoa de aflição e paciência, como se vê no Flos sanctorum. A parte inferior do semblante rebelava-se; um canto dos lábios franzia-se em contração constante de odiento desprezo. Franco não ria nunca. Sorria apenas, assistindo a uma briga séria, interessando-se pelo desenlace como um apostador de rinha, enfurecendo-se quando apartavam. Uma queda alegrava-o, principalmente perigosa. Vivia isolado no circulo da excomunhão com que o diretor, invariavelmente, o fulminava todas as manhãs, lendo no refeitório perante o colégio as notas da véspera. </p>

<p>Os professores já sabiam. À nota do Franco, sempre má, devia seguir-se especial comentário deprimente, que a opinião esperava e ouvia com delícia, fartando-se de desprezar. Nenhum de nós como ele! E o zelo do mestre cada dia retemperava o velho anátema. Não convinha expulsar. Uma coisa destas aproveita-se como um bibelô do ensino intuitivo, explora-se como a miséria do hilota, para a lição fecunda do asco. A própria indiferença repugnante da vitima é útil. </p>

<p>Três anos havia que o infeliz, num suplício de pequeninas humilhações cruéis, agachado, abatido, esmagado, sob o peso das virtudes alheias mais que das próprias culpas, ali estava, — cariátide forçada no edifício de moralização do Ateneu, exemplar perfeito de depravação oferecido ao horror santo dos puros. </p>

<p>Várias vezes nessa tarde fui assaltado pela chacota impertinente do Barbalho. O endemoninhado caolho puxava-me a roupa, esbarrava-me encontrões e fugia com grandes risadas falsas, ou parava-me de súbito em frente, e revestindo-se de quanta seriedade lhe era suscetível o açafrão da cara, perguntava: “Mudas as calças?” Um inferno. Até que afinal o meu desespero estourou. </p>

<p>Foi à noite, pouco antes da ceia. Estávamos a um canto mal iluminado do pátio, quase sós. O biltre reconheceu-me e arreganhou uma inexprimível interjeição de mofa. Não esperei por mais. Estampei-lhe uma bofetada. Meio segundo depois, rolávamos na poeira, engalfinhados como feras. Uma luta rápida. Avisaram-nos que vinha o Silvino. Barbalho evadiu-se. Eu verifiquei que tinha o peito da blusa coberto de sangue que me corria do nariz. </p>

<p>Uma hora mais tarde, na cama de ferro do salão azul, compenetrado da tristeza de hospital dos dormitórios, fundos na sombra do gás mortiço, trincando a colcha branca, eu meditava o retrospecto do meu dia. </p>

<p>Era assim o colégio. Que fazer da matalotagem dos meus planos? </p>

<p>Onde meter a máquina dos meus ideais naquele mundo de brutalidade, que me intimidava com os obscuros detalhes e as perspectivas informes, escapando à investigação da minha inexperiência? Qual o meu destino, naquela sociedade que o Rebelo descrevera horrorizado, com as meias frases de mistério, suscitando temores indefinidos, recomendando energia, como se coleguismo fosse hostilidade? De que modo alinhar a norma generosa e sobranceira de proceder com a obsessão pertinaz do Barbalho? Inutilmente buscara reconhecer no rosto dos rapazes o nobre aspecto da solenidade dos prêmios, dando-me idéia da legião dos soldados do trabalho, que fraternizavam no empenho comum, unidos pelo coração e pela vantagem do coletivo esforço. Individualizados na debandada do receio, com as observações ainda mais da critica do Rebelo, bem diverso sentimento inspiravam-me. A reação do contraste induzia-me a um conceito de repugnância que o hábito havia de esmorecer, que me tirava lágrimas àquela noite. Ao mesmo tempo oprimia-me o pressentimento da solidão moral, fazendo adivinhar que as preocupações mínimas e as concomitantes surpresas inconfessáveis dariam pouco para as efusões de alívio, a que corresponde o conselho, a consolação. </p>

<p>Nada de protetor, dissera Rebelo. Era o ermo. E, na solidão, conspiradas, as adversidades de toda a espécie, falsidade traiçoeira dos afetos, perseguição da malevolência, espionagem da vigilância; por cima de tudo, céu de trovões sobre os desalentos, a fúria tonante de Júpiter-diretor, o tremendo Aristarco dos momentos graves. </p>

<p>Lembranças da família desviaram-me o curso às reflexões. Não havia mais a mão querida para acalentar-me o primeiro sono, nem a oração, tão longe nesse momento, que me protegia à noite como um dossel de amor; o abandono apenas das crianças sem lar que os asilos da miséria recolhem. </p>

<p>A convicção do meu triste infortúnio lentamente, suavemente, aniquilou-me num conforto de prostração e eu dormi. </p>

<p>Pela noite adentro, comparsas de pesadelo, perseguiram-me as imagens várias do atribulado dia; a pegajosa ternura do Sanches, a cara amarela do Barbalho, a expressão de tortura do Franco, os frades descompostos do roupeiro. Sonhei mesmo em regra. Eu era o Franco. A minha aula, o colégio inteiro, mil colégios, arrebatados, num pé-de-vento, voavam léguas afora por uma planície sem termo. Gritavam todos, urravam a sabatina de tatuadas com um entusiasmo de turbilhão. O pó crescia em nuvens do solo; a massa confusa ouriçava-se de gestos, gestos de galho sem folhas em tormenta agoniada de inverno; sobre a floresta dos braços, gesto mais alto, gesto vencedor, a mão magra do Maurílio, crescida, enorme, preta, torcendo, destorcendo os dedos sôfregos, convulsionados da histeria do quinau... E eu caia, único vencido! E o tropel, de volta, vinha sobre mim, todos sobre mim! sopeavam-me, calcavam-me, pesados, carregando prêmios, prêmios aos cestos! </p>

<p>A sineta, tocando a despertar, livrou-me da angústia. Cinco horas da manhã. </p>


                <br />  <br />  <br />  <br />  <br />  <br /> 
         </div>
      </div>     
</asp:Content>
